;;; modus-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from modus-operandi-deuteranopia-theme.el

(register-definition-prefixes "modus-operandi-deuteranopia-theme" '("modus-operandi-deuteranopia-palette-"))


;;; Generated autoloads from modus-operandi-theme.el

(register-definition-prefixes "modus-operandi-theme" '("modus-operandi-palette-"))


;;; Generated autoloads from modus-operandi-tinted-theme.el

(register-definition-prefixes "modus-operandi-tinted-theme" '("modus-operandi-tinted-palette-"))


;;; Generated autoloads from modus-operandi-tritanopia-theme.el

(register-definition-prefixes "modus-operandi-tritanopia-theme" '("modus-operandi-tritanopia-palette-"))


;;; Generated autoloads from modus-themes.el

(autoload 'modus-themes-contrast "modus-themes" "\
Measure WCAG contrast ratio between COLOR-1 and COLOR-2.
Color values are of the form accepted by `modus-themes-wcag-formula'.

(fn COLOR-1 COLOR-2)")
(autoload 'modus-themes-activate "modus-themes" "\
Load THEME if neeeded, so that it can be used by other commands.

(fn THEME)")
(autoload 'modus-themes-select "modus-themes" "\
Load a Modus THEME using minibuffer completion.
With optional prefix argument, prompt to limit the set of themes to
either dark or light variants.

Run `modus-themes-after-load-theme-hook' after loading the theme.
Disable other themes per `modus-themes-disable-other-themes'.

(fn THEME)" t)
(autoload 'modus-themes-select-dark "modus-themes" "\
Like `modus-themes-select' for a dark THEME.

(fn THEME)" t)
(autoload 'modus-themes-select-light "modus-themes" "\
Like `modus-themes-select' for a light THEME.

(fn THEME)" t)
(autoload 'modus-themes-toggle "modus-themes" "\
Toggle between the two `modus-themes-to-toggle'.
If `modus-themes-to-toggle' does not specify two Modus themes,
prompt with completion for a theme among our collection (this is
practically the same as the `modus-themes-select' command).

Run `modus-themes-after-load-theme-hook' after loading the theme.
Disable other themes per `modus-themes-disable-other-themes'." t)
(function-put 'modus-themes-toggle 'interactive-only 't)
(autoload 'modus-themes-rotate "modus-themes" "\
Rotate to the next theme among THEMES.
When called interactively THEMES is the value of `modus-themes-to-rotate'
and REVERSE is the prefix argument.

If the current theme is already the next in line, then move to the one
after.  The rotation is performed rightwards if REVERSE is nil (the
default), and leftwards if REVERSE is non-nil.  Perform the rotation
such that the current element in the list becomes the last.  Do not
modify THEMES in the process.

(fn THEMES &optional REVERSE)" t)
(autoload 'modus-themes-load-random "modus-themes" "\
Load a Modus theme at random, excluding the current one.

With optional BACKGROUND-MODE as a prefix argument, prompt to limit the
set of themes to either dark or light variants.  When called from Lisp,
BACKGROUND-MODE is either the `dark' or `light' symbol.

Run `modus-themes-after-load-theme-hook' after loading a theme.

(fn &optional BACKGROUND-MODE)" t)
(autoload 'modus-themes-load-random-dark "modus-themes" "\
Load a random dark theme." t)
(function-put 'modus-themes-load-random-dark 'interactive-only 't)
(autoload 'modus-themes-load-random-light "modus-themes" "\
Load a random light theme." t)
(function-put 'modus-themes-load-random-light 'interactive-only 't)
(autoload 'modus-themes-theme "modus-themes" "\
Define a Modus theme or derivative thereof.
NAME is the name of the new theme.  FAMILY is the collection of themes
it belongs to.  DESCRIPTION is its documentation string.
BACKGROUND-MODE is either `dark' or `light', in reference to the theme's
background color.  The CORE-PALETTE, USER-PALETTE, and OVERRIDES-PALETTE
are symbols of variables which define palettes commensurate with
`modus-themes-operandi-palette'.

The optional CUSTOM-FACES and CUSTOM-VARIABLES are joined together with
the `modus-themes-faces' and `modus-themes-custom-variables',
respectively.  A derivative theme defining those is thus overriding what
the Modus themes have by default.

Consult the manual for details on how to build a theme on top of the
`modus-themes': Info node `(modus-themes) Build on top of the Modus themes'.

(fn NAME FAMILY DESCRIPTION BACKGROUND-MODE CORE-PALETTE USER-PALETTE OVERRIDES-PALETTE &optional CUSTOM-FACES CUSTOM-VARIABLES)")
(defvar modus-themes-include-derivatives-mode nil "\
Non-nil if Modus-Themes-Include-Derivatives mode is enabled.
See the `modus-themes-include-derivatives-mode' command
for a description of this minor mode.")
(custom-autoload 'modus-themes-include-derivatives-mode "modus-themes" nil)
(autoload 'modus-themes-include-derivatives-mode "modus-themes" "\
When enabled, all Modus themes commands cover derivatives as well.

Otherwise, they only consider the `modus-themes-items'.

Derivative theme projects can implement the equivalent of this minor
mode plus a method for `modus-themes-get-themes' to filter themes
accordingly.

This is a global minor mode.  If called interactively, toggle the
`Modus-Themes-Include-Derivatives mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='modus-themes-include-derivatives-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'modus-themes-generate-palette "modus-themes" "\
Generate a palette given the BASE-COLORS.
BASE-COLORS consists of lists in the form (NAME VALUE).  NAME is at
least a symbol of `bg-main' or `fg-main', while VALUE is a string
representing a color either by name like in `list-colors-display' or
hexadecimal RGB of the form #123456.  See the value of a core Modus
palette, like `modus-themes-operandi-palette' for all current NAME
symbols.

BASE-COLORS is used to derive a palette.  Any entry whose name is
already present in BASE-COLORS is not derived but taken as-is.  The rest
are generated automatically.  The generated palette can be used as-is by
a derivative theme (per `modus-themes-theme') or as a starting point for
further refinements.

With optional COOL-OR-WARM-PREFERENCE as a symbol of either `cool' or
`warm' make relevant color choices for derivative values.  If
COOL-OR-WARM-PREFERENCE is nil, derive the implied preference from the
value of the `bg-main' color in BASE-COLORS.  If the value of `bg-main'
satisfies `color-gray-p', then fall back to `cool'.  For our purposes,
`cool' means that the color is closer to pure blue than pure red, while
`warm' is the opposite.

With optional CORE-PALETTE use it to fill in any of the remaining
entries.  This can be a symbol like `modus-themes-operandi-palette'.  Do
not try to enforce a core palette among those defined in modus-themes.el
and let the user assume responsibility for any incompatibilities.  If
CORE-PALETTE is nil, then infer a suitable palette based on whether the
`bg-main' value in BASE-COLORS is light or dark and then the
COOL-OR-WARM-PREFERENCE.  This inferred palette will be
`modus-themes-operandi-palette' for a light `bg-main' and
`modus-themes-vivendi-palette' for a dark `bg-main'.  The `cool' or
`warm' shall yield the tinted variants of those palettes, namely,
`modus-themes-operandi-tinted-palette' and
`modus-themes-vivendi-tinted-palette'.

With optional MAPPINGS use them instead of trying to derive new ones.
If MAPPINGS is nil, generate some essential color mappings and let the
rest come from CORE-PALETTE.

(fn BASE-COLORS &optional COOL-OR-WARM-PREFERENCE CORE-PALETTE MAPPINGS)")
(when load-file-name (let ((dir (file-name-directory load-file-name))) (unless (equal dir (expand-file-name "themes/" data-directory)) (add-to-list 'custom-theme-load-path dir))))
(register-definition-prefixes "modus-themes" '("modus-themes-"))


;;; Generated autoloads from modus-vivendi-deuteranopia-theme.el

(register-definition-prefixes "modus-vivendi-deuteranopia-theme" '("modus-vivendi-deuteranopia-palette-"))


;;; Generated autoloads from modus-vivendi-theme.el

(register-definition-prefixes "modus-vivendi-theme" '("modus-vivendi-palette-"))


;;; Generated autoloads from modus-vivendi-tinted-theme.el

(register-definition-prefixes "modus-vivendi-tinted-theme" '("modus-vivendi-tinted-palette-"))


;;; Generated autoloads from modus-vivendi-tritanopia-theme.el

(register-definition-prefixes "modus-vivendi-tritanopia-theme" '("modus-vivendi-tritanopia-palette-"))

;;; End of scraped data

(provide 'modus-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; modus-themes-autoloads.el ends here
