;;; jinja2-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jinja2-mode.el

(autoload 'jinja2-mode "jinja2-mode" "\
Major mode for editing jinja2 files

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.jinja2\\'" . jinja2-mode))
(add-to-list 'auto-mode-alist '("\\.j2\\'" . jinja2-mode))
(register-definition-prefixes "jinja2-mode" '("jinja2-" "sgml-indent-line-num"))

;;; End of scraped data

(provide 'jinja2-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jinja2-mode-autoloads.el ends here
