;;; consult-flycheck-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-flycheck.el

(autoload 'consult-flycheck "consult-flycheck" "\
Jump to flycheck error." t)
(register-definition-prefixes "consult-flycheck" '("consult-flycheck--"))

;;; End of scraped data

(provide 'consult-flycheck-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-flycheck-autoloads.el ends here
