;;; magit-imerge-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from magit-imerge.el

(autoload 'magit-imerge-merge "magit-imerge" "\
Incrementally merge BRANCH into the current branch.
$ git imerge merge [ARGS] BRANCH

(fn BRANCH &optional ARGS)" t)
(autoload 'magit-imerge-rebase "magit-imerge" "\
Incrementally rebase the current branch onto BRANCH.
$ git imerge rebase [ARGS] BRANCH

(fn BRANCH &optional ARGS)" t)
(autoload 'magit-imerge-revert "magit-imerge" "\
Incrementally revert COMMIT.

If a region selects multiple commits, revert all of them.

$ git imerge revert [ARGS] COMMIT
$ git imerge drop [ARGS] <range>

(fn COMMIT &optional ARGS)" t)
(autoload 'magit-imerge-drop "magit-imerge" "\
Incrementally drop COMMIT from the current branch.

If a region selects multiple commits, drop all of them.

$ git imerge drop [ARGS] COMMIT
$ git imerge drop [ARGS] <range>

(fn COMMIT &optional ARGS)" t)
(autoload 'magit-imerge-resume "magit-imerge" "\
Resume an incremental merge.
This can resume a previous git-imerge sequence that was suspended
with `magit-imerge-suspend'.  More generally, it marks a previous
incremental merge as the active one." t)
 (autoload 'magit-imerge "magit-imerge" nil t)
(register-definition-prefixes "magit-imerge" '("magit-imerge-"))

;;; End of scraped data

(provide 'magit-imerge-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-imerge-autoloads.el ends here
