;;; fontaine-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from fontaine.el

(autoload 'fontaine-set-preset "fontaine" "\
Set font configurations specified in PRESET.
PRESET is a symbol that represents the car of a list in
`fontaine-presets'.  When called interactively, prompt for
PRESET.

Set `fontaine-current-preset' to PRESET.  Call
`fontaine-set-preset-hook' as a final step after setting the PRESET.

(fn PRESET)" t)
(autoload 'fontaine-toggle-preset "fontaine" "\
Toggle between the last two known Fontaine presets.
These are the presets that were set with `fontaine-set-preset'.  If
there are no two selected presets, then prompt the user to set a preset.

As a final step, call the `fontaine-set-preset-hook'." t)
(autoload 'fontaine-store-latest-preset "fontaine" "\
Write latest state to `fontaine-latest-state-file'.
Can be assigned to `kill-emacs-hook'.")
(autoload 'fontaine-restore-latest-preset "fontaine" "\
Restore latest preset set by `fontaine-set-preset'.
The value is stored in `fontaine-latest-state-file'.")
(defvar fontaine-mode nil "\
Non-nil if Fontaine mode is enabled.
See the `fontaine-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `fontaine-mode'.")
(custom-autoload 'fontaine-mode "fontaine" nil)
(autoload 'fontaine-mode "fontaine" "\
Persist Fontaine presets.

Arrange to store and restore the current Fontaine preset when
closing and restarting Emacs.

This is a global minor mode.  If called interactively, toggle the
`Fontaine mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='fontaine-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "fontaine" '("fontaine-"))

;;; End of scraped data

(provide 'fontaine-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fontaine-autoloads.el ends here
