;;; consult-dir-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-dir.el

(autoload 'consult-dir-jump-file "consult-dir" "\
Jump to file from the directory in the minibuffer prompt." t)
(autoload 'consult-dir "consult-dir" "\
Choose a directory and act on it.

The action taken on the directory is the value of
`consult-dir-default-command.  The default is to call
`find-file' starting at this directory.

When called from the minibuffer, insert the directory into the
minibuffer prompt instead.  Existing minibuffer contents will be
shadowed or deleted depending on the value of
`consult-dir-shadow-filenames'.

The list of sources for directory paths is
`consult-dir-sources', which can be customized." t)
(register-definition-prefixes "consult-dir" '("consult-dir-"))

;;; End of scraped data

(provide 'consult-dir-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-dir-autoloads.el ends here
