;;; evil-string-inflection-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-string-inflection.el

(autoload 'evil-string-inflection "evil-string-inflection.el" "\
Define a new evil operator that cicles underscore -> UPCASE -> CamelCase." t)

;;; End of scraped data

(provide 'evil-string-inflection-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-string-inflection-autoloads.el ends here
