#!/bin/sh

# Change to script directory
cd $(dirname $(readlink -f $0))

# Be verbose
set -x

# Stop on first error
set -e

# Go to child directory and source make-symlinks
if [ -d "$1" ]; then
	cd $1
	source ./make-symlinks
else
	echo "Directory ${1} does not exist"
	exit 1
fi
