;;; no-littering-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from no-littering.el

(autoload 'no-littering-expand-etc-file-name "no-littering" "\
Expand filename FILE relative to `no-littering-etc-directory'.

(fn FILE)")
(autoload 'no-littering-expand-var-file-name "no-littering" "\
Expand filename FILE relative to `no-littering-var-directory'.

(fn FILE)")
(register-definition-prefixes "no-littering" '("no-littering-"))

;;; End of scraped data

(provide 'no-littering-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; no-littering-autoloads.el ends here
