;;; zeal-at-point-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from zeal-at-point.el

(autoload 'zeal-at-point "zeal-at-point" "\
Search for the word at point in Zeal.

(fn &optional EDIT-SEARCH)" t)
(autoload 'zeal-at-point-set-docset "zeal-at-point" "\
Set current buffer's docset." t)
(autoload 'zeal-at-point-search "zeal-at-point" "\
Prompt and search in zeal.

(fn &optional EDIT-SEARCH)" t)
(register-definition-prefixes "zeal-at-point" '("zeal-at-point-"))

;;; End of scraped data

(provide 'zeal-at-point-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; zeal-at-point-autoloads.el ends here
