;;; evil-text-object-python-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-text-object-python.el

 (autoload 'evil-text-object-python-inner-statement "evil-text-object-python" nil t)
 (autoload 'evil-text-object-python-outer-statement "evil-text-object-python" nil t)
 (autoload 'evil-text-object-python-function "evil-text-object-python" nil t)
(autoload 'evil-text-object-python-add-bindings "evil-text-object-python" "\
Add text object key bindings.

This function should be added to a major mode hook.  It modifies
buffer-local keymaps and adds bindings for Python text objects for
both operator state and visual state." t)
(register-definition-prefixes "evil-text-object-python" '("evil-text-object-python-"))

;;; End of scraped data

(provide 'evil-text-object-python-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-text-object-python-autoloads.el ends here
