;;; gsettings-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gsettings.el

(autoload 'gsettings-apply-gnome-settings "gsettings" "\
Apply some Gnome desktop configuration to Emacs." t)
(register-definition-prefixes "gsettings" '("gsettings-"))

;;; End of scraped data

(provide 'gsettings-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gsettings-autoloads.el ends here
