#!/bin/sh

set -e
set -x

cd external/

git clone https://github.com/ehamberg/vim-cute-python vim-cute-python
git clone https://github.com/jimf/vim-pep8-text-width.git pep8-text-width
git clone https://github.com/laurentb/vim-cute-php.git vim-cute-php
git clone https://github.com/msanders/snipmate.vim.git snipmate
git clone https://github.com/scrooloose/syntastic.git syntastic
git clone https://github.com/tpope/vim-abolish.git abolish
git clone https://github.com/tpope/vim-commentary.git commentary
git clone https://github.com/tpope/vim-eunuch.git eunuch
git clone https://github.com/tpope/vim-pathogen.git pathogen
git clone https://github.com/tpope/vim-repeat.git repeat
git clone https://github.com/tpope/vim-surround.git surround
git clone https://github.com/tpope/vim-unimpaired.git unimpaired

find . -name .git -print0 |xargs -0 rm -fr
