;;; autorevert-tail-truncate-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from autorevert-tail-truncate.el

(autoload 'auto-revert-tail-truncate-mode "autorevert-tail-truncate" "\
`auto-revert-tail-mode' with automatic buffer line truncation.

Truncation does not affect the content of underlying file, only the
buffer in which it is displayed.

Customize `auto-revert-tail-mode-hook' to control features such as
`truncate-lines' for the tailed buffer.

This is a minor mode.  If called interactively, toggle the
`Auto-Revert-Tail-Truncate mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `auto-revert-tail-truncate-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'auto-revert-tail-truncate-file "autorevert-tail-truncate" "\
Prompt for a file to tail using `auto-revert-tail-truncate-mode'.
Invoke programmatically specifying FILENAME.

(fn FILENAME)" t)
(register-definition-prefixes "autorevert-tail-truncate" '("auto-revert-" "turn-on-auto-revert-tail-truncate-mode"))

;;; End of scraped data

(provide 'autorevert-tail-truncate-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; autorevert-tail-truncate-autoloads.el ends here
