" Vim configuration (gvim)

set lines=60 columns=120
set guioptions-=m guioptions-=T guioptions+=L
set guicursor=a:blinkon0 

colorscheme mustang

" Smooth scrolling (and try to avoid over SSH)
if (stridx(expand("$DISPLAY"), ":") == 0)
  SmoothScrolling
endif

" Fonts
if !exists("g:font_initialized")
  let g:font_initialized = 1
  if has("gui_gtk2")
    if (g:gnome_active)
      "let &guifont = substitute(system("gconftool --get /desktop/gnome/interface/monospace_font_name"), "\n", "", "")
      let &guifont = substitute(substitute(system("dconf read /org/gnome/desktop/interface/monospace-font-name"), "\n", "", ""), "'", "", "g")
    else
      set guifont=Monospace\ 10
    endif
  endif
endif

" Save using Ctrl-S
noremap <C-s> :update<Return>
inoremap <C-s> <C-O>:update<Return>

" Keyboard shortcuts to change the text size
noremap <C-kMinus> :SmallerFont<Return>
noremap <C-kPlus> :LargerFont<Return>
noremap <C-ScrollWheelDown> :SmallerFont<Return>
noremap <C-ScrollWheelUp> :LargerFont<Return>
