" Vim configuration (gvim)

" Window layout
set lines=60 columns=120
set guioptions-=m go-=r go-=L go-=T
set guicursor=a:blinkon0

" Colors
set background=light
colorscheme default

" Fonts
if $XDG_SESSION_DESKTOP == "gnome"
  let &guifont = substitute(system("gsettings get org.gnome.desktop.interface monospace-font-name"), "\[\n'\]", "", "g")
else
  set guifont=Monospace\ 10
endif

" Save using Ctrl-S
noremap <C-s> :update<Return>
inoremap <C-s> <C-O>:update<Return>

" Keyboard shortcuts to change the text size (fontzoom plugin)
silent! nmap <unique> <silent> <C-kPlus> <Plug>(fontzoom-larger)
silent! nmap <unique> <silent> <C-kMinus> <Plug>(fontzoom-smaller)
silent! nmap <unique> <silent> <C-ScrollWheelUp> <Plug>(fontzoom-larger)
silent! nmap <unique> <silent> <C-ScrollWheelDown> <Plug>(fontzoom-smaller)
