#!/bin/sh

set -e

if [ -d "external.old/" ]; then
    echo "The directory external.old/ already exists. Remove it first."
    exit 1
fi

set -x

mv external external.old
mkdir external
cd external/

git clone https://github.com/altercation/vim-colors-solarized.git colors-solarized
git clone https://github.com/groenewege/vim-less.git less
git clone https://github.com/jimf/vim-pep8-text-width.git pep8-text-width
git clone https://github.com/Lokaltog/vim-powerline.git powerline
git clone https://github.com/msanders/snipmate.vim.git snipmate
git clone https://github.com/scrooloose/syntastic.git syntastic
git clone https://github.com/thinca/vim-fontzoom.git fontzoom
git clone https://github.com/tpope/vim-abolish.git abolish
git clone https://github.com/tpope/vim-commentary.git commentary
git clone https://github.com/tpope/vim-eunuch.git eunuch
git clone https://github.com/tpope/vim-fugitive.git fugitive
git clone https://github.com/tpope/vim-pathogen.git pathogen
git clone https://github.com/tpope/vim-repeat.git repeat
git clone https://github.com/tpope/vim-surround.git surround
git clone https://github.com/tpope/vim-unimpaired.git unimpaired

find . -name .git -print0 |xargs -0 rm -fr
find . -name .gitignore -delete
