" Vim configuration

set nocompatible

" Display
set display=lastline,uhex laststatus=2 ruler
set showmatch
set backspace=2 whichwrap=b,s,h,l,<,>,[,]
set nofoldenable foldmethod=marker
silent! set listchars=eol:$,trail:_,extends:»,precedes:«,tab:»·,nbsp:~

" Movement
noremap <C-h> h
noremap <C-j> gj
noremap <C-k> gk
noremap <C-l> l
noremap <Down> gj
noremap <Up> gk

" Scrolling
set scrolloff=5 sidescrolloff=5
map <Space> <C-D>
map <S-Space> <C-U>
map <Backspace> <C-U>
map <S-Backspace> <C-D>

" Encoding
set encoding=utf-8

" Indentation
set expandtab shiftwidth=4 tabstop=4
set autoindent smartindent

" Wrapping
set linebreak nojoinspaces
let &showbreak="↪ "
set colorcolumn=+1

" Search/replace
set ignorecase smartcase
set hlsearch incsearch
nohlsearch
set gdefault

" Whitespace (after an abbreviation)
function! EatWhitespace()
	let c = nr2char(getchar())
	return (c =~ '\s') ? '' : c
endfunction
command! StripTrailingWhitespace normal mx<Enter>:%s/\s\+$//<Enter>:nohlsearch<Enter>`x
nnoremap <F12> :StripTrailingWhitespace<Return>

" Easy paragraph formatting
noremap Q gqap

" Quickly move to end of line in insert mode
inoremap <C-L> <C-O>A

" Break undo sequence before killing the line
" then intended and it cannot be undone.
inoremap <C-U> <C-G>u<C-U>

" Pressing p should replace selected text in visual mode
vnoremap p <Esc>:let current_reg = @"<CR>gvdi<C-R>=current_reg<CR><Esc>

" Spell checking
command! SpellDutch   setlocal spell spelllang=nl
command! SpellEnglish setlocal spell spelllang=en
command! NoSpell      setlocal nospell

" No sync I/O and avoid local cruft; we have VCS'es to keep files safe
set nofsync swapsync=
set directory-=.

" Opening/switching files
set hidden
set autochdir
set suffixes+=.aux,.bbl,.blg,.dvi,.idx,.log,.out,.pdf,.toc,.pyc,.pyo

" Active Gnome session?
let g:gnome_active = exists("$GNOME_DESKTOP_SESSION_ID")

" Development
nnoremap <F9> :make<Return>
setlocal tags=tags;/

" Concealing
function! ToggleConceal()
  if &conceallevel != '0'
    set conceallevel=0
  else
    set conceallevel=2
  endif
endfunction

" Miscellaneous shortcuts
let mapleader = ","
map <silent> <Leader>l :set list!<Return>
map <silent> <Leader>w :set wrap!<Return>
map <silent> <Leader>n :set number!<Return>
map <silent> <Leader>/ :nohlsearch<Return>
map <silent> <Leader>c :call ToggleConceal()<Return>

" FIXME: does the repeat.vim plugin cover this?
"" Make "repeat last action" also work in visual mode
"vnoremap . :normal .<Return>

" Load plugins using pathogen
runtime bundle/external/pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#runtime_append_all_bundles('bundle/external')
"
" File type specific configuration and enable syntax highlighting
filetype plugin indent on
syntax on
