" Vim configuration

if exists("+autochdir")
  set autochdir
endif
set autoindent
set colorcolumn=+1
set display+=uhex
set encoding=utf-8
set expandtab
set gdefault
set hidden
set hlsearch
set ignorecase
set linebreak
set listchars=eol:$,trail:_,extends:»,precedes:«,tab:»·,nbsp:~
let mapleader = ","
set nojoinspaces
set scrolloff=5
set shiftwidth=4
let &showbreak="↪ "
set showcmd
set showmatch
set sidescrolloff=5
set smartcase
set smartindent
set tabstop=4
set whichwrap=b,s,h,l,<,>,[,]

nohlsearch

command! NoSpell      setlocal nospell
command! SpellDutch   setlocal spell spelllang=nl
command! SpellEnglish setlocal spell spelllang=en
command! -range=% StripTrailingWhitespace <line1>,<line2>s/\s\+$//e

nnoremap <Backspace> <C-U>
nnoremap <S-Backspace> <C-D>
nnoremap <S-Space> <C-U>
nnoremap <Space> <C-D>
nnoremap <silent> <Leader><Space> :StripTrailingWhitespace<Return>
nnoremap Q gqap
noremap <Down> gj
noremap <Up> gk

" Colors
function! ColorSchemeFromFlagFile() abort
  let l:exists = filereadable(expand('~/.config/dark-theme'))
  let &background = l:exists ? 'dark' : 'light'
endfunction
command ColorSchemeFromFlagFile call ColorSchemeFromFlagFile()
let g:solarized_italics = 0
let g:solarized_termtrans = 1
colorscheme solarized8
