;;; vue-html-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vue-html-mode.el

(autoload 'vue-html-mode "vue-html-mode" "\
Major mode for Vue.js templates.

(fn)" t)
(register-definition-prefixes "vue-html-mode" '("vue-html-"))

;;; End of scraped data

(provide 'vue-html-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vue-html-mode-autoloads.el ends here
