;;; terminal-here-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from terminal-here.el

(autoload 'terminal-here-launch "terminal-here" "\
Launch a terminal in the current working directory.

This is the directory of the current buffer unless you have
changed it by running `cd'.

(fn &optional INNER-COMMAND)" t)
(defalias 'terminal-here 'terminal-here-launch)
(autoload 'terminal-here-project-launch "terminal-here" "\
Launch a terminal in the current project root.

Uses `terminal-here-project-root-function' to determine the
project root.

(fn &optional INNER-COMMAND)" t)
(register-definition-prefixes "terminal-here" '("terminal-here-"))

;;; End of scraped data

(provide 'terminal-here-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; terminal-here-autoloads.el ends here
