;;; multi-line-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from multi-line.el

(autoload 'multi-line-enable-mode-hooks "multi-line" "\
Set default language specific strategies for multi-line." t)
(autoload 'multi-line-disable-mode-hooks "multi-line" "\
Remove default language specific strategies for multi-line." t)
(autoload 'multi-line "multi-line" "\
Multi-line the statement at point.

When ARG is provided single-line the statement at point instead.

(fn ARG)" t)
(autoload 'multi-line-single-line "multi-line" "\
Single-line the statement at point." t)
(register-definition-prefixes "multi-line" '("multi-line-"))


;;; Generated autoloads from multi-line-candidate.el

(register-definition-prefixes "multi-line-candidate" '("multi-line-candidate"))


;;; Generated autoloads from multi-line-cycle.el

(register-definition-prefixes "multi-line-cycle" '("multi-line-"))


;;; Generated autoloads from multi-line-decorator.el

(register-definition-prefixes "multi-line-decorator" '("multi-line-"))


;;; Generated autoloads from multi-line-enter.el

(register-definition-prefixes "multi-line-enter" '("multi-line-"))


;;; Generated autoloads from multi-line-find.el

(register-definition-prefixes "multi-line-find" '("multi-line-"))


;;; Generated autoloads from multi-line-highlight.el

(autoload 'multi-line-clear-highlights "multi-line-highlight" "\
Remove any existing multi-line highlight overlays." t)
(autoload 'multi-line-highlight-current-candidates "multi-line-highlight" "\
Highlight the positions at which multi-line will consider adding newlines." t)
(register-definition-prefixes "multi-line-highlight" '("multi-line-"))


;;; Generated autoloads from multi-line-respace.el

(register-definition-prefixes "multi-line-respace" '("multi-line-"))


;;; Generated autoloads from multi-line-shared.el

(register-definition-prefixes "multi-line-shared" '("multi-line-"))

;;; End of scraped data

(provide 'multi-line-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; multi-line-autoloads.el ends here
