;;; shift-number-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from shift-number.el

(autoload 'shift-number-up "shift-number" "\
Increase the number at point (or on the current line) by ARG.

(fn &optional ARG)" t)
(autoload 'shift-number-down "shift-number" "\
Decrease the number at point (or on the current line) by ARG.

(fn &optional ARG)" t)
(autoload 'shift-number-up-incremental "shift-number" "\
Incrementally increase numbers between point and mark by ARG.
The first number is increased by ARG, the second by 2*ARG, etc.
Works with rectangle selection when `rectangle-mark-mode' is active.

(fn &optional ARG)" t)
(autoload 'shift-number-down-incremental "shift-number" "\
Incrementally decrease numbers between point and mark by ARG.
The first number is decreased by ARG, the second by 2*ARG, etc.
Works with rectangle selection when `rectangle-mark-mode' is active.

(fn &optional ARG)" t)
(autoload 'shift-number-increment-at-point-with-search "shift-number" "\
Change the number at point, with keyword arguments in ARGS.

Required keywords:
  :amount       - The amount to increment.
  :range        - A cons cell (BEG . END) specifying search bounds.

Optional keywords:
  :dir          - Search direction: 1 for forward, -1 for backward (default 1).
  :range-check-fn - See `shift-number--inc-at-pt-impl-with-match-chars'.

Optional keywords to override customization variables:
  :pad-default    - Override `shift-number-pad-default'.
  :negative       - Override `shift-number-negative'.
  :separator-chars - Override `shift-number-separator-chars'.
  :case           - Override `shift-number-case'.
  :motion         - Override `shift-number-motion'.

Return (OLD-BEG . OLD-END) on success, nil on failure.
Point is left at the end of the modified number.

This function is only exposed for use by `evil-numbers'.

(fn &rest ARGS)")
(register-definition-prefixes "shift-number" '("shift-number-"))

;;; End of scraped data

(provide 'shift-number-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; shift-number-autoloads.el ends here
