;;; mmm-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mmm-auto.el

(register-definition-prefixes "mmm-auto" '("mmm-"))


;;; Generated autoloads from mmm-class.el

(register-definition-prefixes "mmm-class" '("mmm-"))


;;; Generated autoloads from mmm-cmds.el

(register-definition-prefixes "mmm-cmds" '("mmm-"))


;;; Generated autoloads from mmm-compat.el

(register-definition-prefixes "mmm-compat" '("mmm-" "skeleton-positions"))


;;; Generated autoloads from mmm-cweb.el

(register-definition-prefixes "mmm-cweb" '("mmm-cweb-"))


;;; Generated autoloads from mmm-erb.el

(autoload 'html-erb-mode "mmm-erb" "\


(fn)" t)
(autoload 'nxml-web-mode "mmm-erb" "\


(fn)" t)
(register-definition-prefixes "mmm-erb" '("html-erb-after-syntax-propertize" "mmm-erb-"))


;;; Generated autoloads from mmm-mason.el

(register-definition-prefixes "mmm-mason" '("mmm-mason-"))


;;; Generated autoloads from mmm-mode.el

(register-definition-prefixes "mmm-mode" '("mmm-"))


;;; Generated autoloads from mmm-myghty.el

(register-definition-prefixes "mmm-myghty" '("mmm-myghty-"))


;;; Generated autoloads from mmm-noweb.el

(register-definition-prefixes "mmm-noweb" '("mmm-"))


;;; Generated autoloads from mmm-region.el

(register-definition-prefixes "mmm-region" '("mmm-"))


;;; Generated autoloads from mmm-rpm.el

(register-definition-prefixes "mmm-rpm" '("mmm-rpm-sh-"))


;;; Generated autoloads from mmm-sample.el

(register-definition-prefixes "mmm-sample" '("mmm-"))


;;; Generated autoloads from mmm-univ.el

(register-definition-prefixes "mmm-univ" '("mmm-univ-get-mode"))


;;; Generated autoloads from mmm-utils.el

(register-definition-prefixes "mmm-utils" '("mmm-"))


;;; Generated autoloads from mmm-vars.el

(autoload 'mmm-add-classes "mmm-vars" "\
Add the submode classes CLASSES to `mmm-classes-alist'.

(fn CLASSES)")
(register-definition-prefixes "mmm-vars" '("mmm-"))

;;; End of scraped data

(provide 'mmm-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mmm-mode-autoloads.el ends here
