;;; typo-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from typo.el

(autoload 'typo-all-completions "typo" "\
Generate all  versions of the STRING using COLLECTION.
COLLECTION and PRED are as defined in `all-completions'.

(fn STRING COLLECTION PRED POINT)")
(autoload 'typo-try-completion "typo" "\
Generate the most probable version of STRING using COLLECTION.
COLLECTION and PRED are as defined in `try-completion'.

(fn STRING COLLECTION PRED POINT &optional METADATA)")
(add-to-list 'completion-styles-alist '(typo typo-try-completion typo-all-completions "Typo-Fixing completion
I.e. when completing \"foobor\", with \"foobar\" in the
completion table, this style would attempt replace it with
\"foobar\", because the two strings are close by."))
(register-definition-prefixes "typo" '("typo-"))

;;; End of scraped data

(provide 'typo-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; typo-autoloads.el ends here
