#!/bin/sh

set -e -u -x


#
# Finder
#

# Allow quitting; also hides desktop icons
# defaults write com.apple.finder QuitMenuItem -bool true

# Include full path in window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Show extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Sort folders first
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Always use list view
defaults write com.apple.Finder FXPreferredViewStyle Nlsv

# Avoid creating .DS_Store files
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Make ~/Library visible
chflags nohidden ~/Library


#
# Dock
#

# Autohide
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide -bool true

# Disable annoying visual distractions.
defaults write com.apple.dock no-bouncing -bool TRUE

