;;; counsel-dash-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from counsel-dash.el

(autoload 'counsel-dash "counsel-dash" "\
Query dash docsets.
INITIAL will be used as the initial input, if given.

(fn &optional INITIAL)" t)
(autoload 'counsel-dash-at-point "counsel-dash" "\
Bring up a `counsel-dash' search interface with symbol at point." t)
(register-definition-prefixes "counsel-dash" '("counsel-dash-"))

;;; End of scraped data

(provide 'counsel-dash-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; counsel-dash-autoloads.el ends here
