;;; evil-easymotion-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-easymotion.el

(autoload 'evilem--collect "evil-easymotion" "\
Repeatedly execute func, and collect the cursor positions into a list

(fn FUNC &optional SCOPE ALL-WINDOWS INITIAL-POINT SORT-KEY COLLECT-POSTPROCESS INCLUDE-INVISIBLE)")
 (autoload 'evilem-motion-forward-word-begin "evil-easymotion" nil t)
 (autoload 'evilem-motion-forward-WORD-begin "evil-easymotion" nil t)
 (autoload 'evilem-motion-forward-word-end "evil-easymotion" nil t)
 (autoload 'evilem-motion-forward-WORD-end "evil-easymotion" nil t)
 (autoload 'evilem-motion-backward-word-begin "evil-easymotion" nil t)
 (autoload 'evilem-motion-backward-WORD-begin "evil-easymotion" nil t)
 (autoload 'evilem-motion-backward-word-end "evil-easymotion" nil t)
 (autoload 'evilem-motion-backward-WORD-end "evil-easymotion" nil t)
 (autoload 'evilem-motion-next-line "evil-easymotion" nil t)
 (autoload 'evilem-motion-previous-line "evil-easymotion" nil t)
 (autoload 'evilem-motion-next-visual-line "evil-easymotion" nil t)
 (autoload 'evilem-motion-previous-visual-line "evil-easymotion" nil t)
 (autoload 'evilem-motion-find-char-to "evil-easymotion" nil t)
 (autoload 'evilem-motion-find-char-to-backward "evil-easymotion" nil t)
 (autoload 'evilem-motion-find-char "evil-easymotion" nil t)
 (autoload 'evilem-motion-find-char-backward "evil-easymotion" nil t)
 (autoload 'evilem-motion-backward-section-begin "evil-easymotion" nil t)
 (autoload 'evilem-motion-backward-section-end "evil-easymotion" nil t)
 (autoload 'evilem-motion-forward-section-begin "evil-easymotion" nil t)
 (autoload 'evilem-motion-forward-section-end "evil-easymotion" nil t)
 (autoload 'evilem-motion-backward-sentence-begin "evil-easymotion" nil t)
 (autoload 'evilem-motion-forward-sentence-begin "evil-easymotion" nil t)
 (autoload 'evilem-motion-search-next "evil-easymotion" nil t)
 (autoload 'evilem-motion-search-previous "evil-easymotion" nil t)
 (autoload 'evilem-motion-search-word-forward "evil-easymotion" nil t)
 (autoload 'evilem-motion-search-word-backward "evil-easymotion" nil t)
 (autoload 'evilem-motion-previous-line-first-non-blank "evil-easymotion" nil t)
 (autoload 'evilem-motion-next-line-first-non-blank "evil-easymotion" nil t)
(autoload 'evilem-default-keybindings "evil-easymotion" "\
Define easymotions for all motions evil defines by default

(fn PREFIX)")
(register-definition-prefixes "evil-easymotion" '("evilem-"))

;;; End of scraped data

(provide 'evil-easymotion-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-easymotion-autoloads.el ends here
