;;; evil-python-movement-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-python-movement.el

(autoload 'evil-python-movement-lsb-lsb "evil-python-movement" nil t)
(autoload 'evil-python-movement-rsb-rsb "evil-python-movement" nil t)
(autoload 'evil-python-movement-lsb-m "evil-python-movement" nil t)
(autoload 'evil-python-movement-rsb-m "evil-python-movement" nil t)
(autoload 'evil-python-movement-lsb-M "evil-python-movement" nil t)
(autoload 'evil-python-movement-rsb-M "evil-python-movement" nil t)
(autoload 'evil-python-movement-lsb-rsb "evil-python-movement" nil t)
(autoload 'evil-python-movement-rsb-lsb "evil-python-movement" nil t)
(register-definition-prefixes "evil-python-movement" '("evil-python-movement-"))

;;; End of scraped data

(provide 'evil-python-movement-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-python-movement-autoloads.el ends here
