;;; xml-format-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xml-format.el

 (autoload 'xml-format-buffer "xml-format" nil t)
 (autoload 'xml-format-region "xml-format" nil t)
 (autoload 'xml-format-on-save-mode "xml-format" nil t)
(register-definition-prefixes "xml-format" '("xml-format-xmllint-"))

;;; End of scraped data

(provide 'xml-format-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xml-format-autoloads.el ends here
