;;; evil-exchange-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-exchange.el

(autoload 'evil-exchange "evil-exchange" "\
Exchange two regions with evil motion." t)
(autoload 'evil-exchange-cancel "evil-exchange" "\
Cancel current pending exchange." t)
(autoload 'evil-exchange-install "evil-exchange" "\
Setting evil-exchange key bindings.")
(autoload 'evil-exchange-cx-install "evil-exchange" "\
Setting evil-exchange key bindings in a vim-compatible way" t)
(register-definition-prefixes "evil-exchange" '("evil-exchange"))

;;; End of scraped data

(provide 'evil-exchange-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-exchange-autoloads.el ends here
