#!/usr/bin/env bash

set -e -u

file=~/.config/dark-theme

gtk_theme_light='Adwaita'
gtk_theme_dark='Adwaita-dark'
# gtk_theme_light='Adapta-Eta'
# gtk_theme_dark='Adapta-Nokto-Eta'
# gtk_theme_light='Arc-solid'
# gtk_theme_dark='Arc-Dark-solid'

gnome_shell_theme_light=''
gnome_shell_theme_dark=''
# gnome_shell_theme_light='Adapta-Eta'
# gnome_shell_theme_dark='Adapta-Nokto-Eta'
# gnome_shell_theme_light='Arc-solid'
# gnome_shell_theme_dark='Arc-Dark-solid'


set_gnome_theme() {
    local gtk_theme gnome_shell_theme
    if [ "$1" = "dark" ]; then
        gtk_theme="$gtk_theme_dark"
        gnome_shell_theme="$gnome_shell_theme_dark"
    else
        gtk_theme="$gtk_theme_light"
        gnome_shell_theme="$gnome_shell_theme_light"
    fi
    gsettings set org.gnome.desktop.interface gtk-theme "${gtk_theme}"
    gsettings set org.gnome.shell.extensions.user-theme name "${gnome_shell_theme}"
}

set_gnome_terminal_theme() {
    # Set the foreground and background color of the first
    # gnome-terminal theme to Solarized dark or light.
    local profile_id profile_path background_color foreground_color
    profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | grep ^: | head -n 1)
    profile_path="/org/gnome/terminal/legacy/profiles:/${profile_id}"
    if [ "$1" = "dark" ]; then
        background_color='rgb(0,43,54)'
        foreground_color='rgb(131,148,150)'
    else
        background_color='rgb(253,246,227)'
        foreground_color='rgb(101,123,131)'
    fi
    dconf write "${profile_path}background-color" "'${background_color}'"
    dconf write "${profile_path}foreground-color" "'${foreground_color}'"
}

notify_emacs() {
    # Notify running Emacs instance.
    if pgrep -u "$(id -u)" emacs > /dev/null; then
        emacsclient -e '(w--set-theme-from-environment)' > /dev/null || true
    fi
}

main() {
    local theme
    if [ -e ${file} ]; then
        rm ${file}
        theme=light
    else
        touch ${file}
        theme=dark
    fi
    set_gnome_theme $theme &
    set_gnome_terminal_theme $theme &
    notify_emacs &
}

main
