;;; evil-indent-plus-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-indent-plus.el

 (autoload 'evil-indent-plus-i-indent "evil-indent-plus" nil t)
 (autoload 'evil-indent-plus-a-indent "evil-indent-plus" nil t)
 (autoload 'evil-indent-plus-i-indent-up "evil-indent-plus" nil t)
 (autoload 'evil-indent-plus-a-indent-up "evil-indent-plus" nil t)
 (autoload 'evil-indent-plus-i-indent-up-down "evil-indent-plus" nil t)
 (autoload 'evil-indent-plus-a-indent-up-down "evil-indent-plus" nil t)
(autoload 'evil-indent-plus-default-bindings "evil-indent-plus" "\
Set the default evil-indent-plus keybindings.")
(register-definition-prefixes "evil-indent-plus" '("evil-indent-plus--"))

;;; End of scraped data

(provide 'evil-indent-plus-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-indent-plus-autoloads.el ends here
