#!/bin/sh

set -e -u -x

#
# main interface
#

gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface clock-show-weekday true
gsettings set org.gnome.desktop.interface cursor-blink false
gsettings set org.gnome.desktop.interface gtk-key-theme "'Emacs'"
gsettings set org.gnome.desktop.interface show-battery-percentage true

gsettings set org.gnome.desktop.calendar show-weekdate true

gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 2700

gsettings set org.gnome.desktop.a11y always-show-universal-access-status true


#
# input devices (keyboard, mouse)
#

gsettings set org.gnome.desktop.input-sources per-window false
gsettings set org.gnome.desktop.input-sources show-all-sources true
gsettings set org.gnome.desktop.input-sources sources "[
    ('xkb', 'us+colemak'),
    ('xkb', 'eu')
]"
gsettings set org.gnome.desktop.input-sources xkb-options "[
    'altwin:swap_lalt_lwin',
    'compose:rctrl',
    'ctrl:nocaps',
    'nbsp:level4'
]"

gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Super>apostrophe']"
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Shift><Super>apostrophe']"

gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true


#
# security
#

gsettings set org.gnome.desktop.notifications show-in-lock-screen false

gsettings set org.gnome.desktop.privacy hide-identity true
gsettings set org.gnome.desktop.privacy show-full-name-in-top-bar false

gsettings set org.gnome.desktop.screensaver lock-delay 300
gsettings set org.gnome.desktop.screensaver show-full-name-in-top-bar false
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "['<Super>BackSpace']"

gsettings set org.gnome.system.location enabled true
gsettings set org.gnome.system.location max-accuracy-level "'country'"

#
# window management
#

gsettings set org.gnome.desktop.wm.preferences action-double-click-titlebar "'toggle-maximize-vertically'"
gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar "'lower'"
gsettings set org.gnome.desktop.wm.preferences audible-bell false
gsettings set org.gnome.desktop.wm.preferences disable-workarounds true
gsettings set org.gnome.desktop.wm.preferences focus-mode "'click'"
gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Super>'
gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
gsettings set org.gnome.desktop.wm.preferences visual-bell false

gsettings set org.gnome.desktop.wm.keybindings close "['<Alt>F4', '<Shift><Super>q', '<Control><Super>q', '<Alt><Super>q']"
gsettings set org.gnome.desktop.wm.keybindings minimize "[]"

gsettings set org.gnome.mutter attach-modal-dialogs false

# maximised/full screen
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Alt>F11', '<Shift><Super>f']"
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Alt>F10', '<Super>f']"

# left/right with </> keys (without shift)
gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Super>comma']"
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Super>period']"

# quick window cycling
gsettings set org.gnome.desktop.wm.keybindings cycle-windows "['<Super>Space']"
gsettings set org.gnome.desktop.wm.keybindings cycle-windows-backward "['<Shift><Super>Space']"

# hjkl-style window/workspace navigation; with colemak keys this is hnei, not hjkl
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Super>i']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Super>h']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Super>n']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Super>e']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Shift><Super>n']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Shift><Super>e']"

# workspaces
gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.desktop.wm.preferences num-workspaces 6
gsettings set org.gnome.shell.keybindings switch-to-application-1 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-2 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-3 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-4 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-5 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-6 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-7 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-8 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-9 "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>1']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>5']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>6']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Super>7']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['<Super>8']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Super>9']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Shift><Super>1']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Shift><Super>2']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Shift><Super>3']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Shift><Super>4']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Shift><Super>5']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Shift><Super>6']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 "['<Shift><Super>7']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 "['<Shift><Super>8']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9 "['<Shift><Super>9']"


#
# screenshots
#

gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot-clip "['Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot "['<Primary>Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot-clip "['<Shift>Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot "['<Primary><Shift>Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip "['<Alt>Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot "['<Primary><Alt>Print']"

#
# shortcuts
#

gsettings set org.gnome.shell.keybindings toggle-overview "['<Super>s']"
gsettings set org.gnome.shell.keybindings focus-active-notification "[]"

gsettings set org.gnome.settings-daemon.plugins.media-keys increase-text-size "['<Super>equal']"
gsettings set org.gnome.settings-daemon.plugins.media-keys decrease-text-size "['<Super>minus']"
gsettings set org.gnome.settings-daemon.plugins.media-keys magnifier-zoom-in "['<Shift><Super>plus']"
gsettings set org.gnome.settings-daemon.plugins.media-keys magnifier-zoom-out "['<Shift><Super>underscore']"
gsettings set org.gnome.settings-daemon.plugins.media-keys magnifier "['<Super><Shift>0']"

gsettings set org.gnome.settings-daemon.plugins.media-keys home "['<Super>g']"
gsettings set org.gnome.settings-daemon.plugins.media-keys www "['<Super>w']"

gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding "'<Super>t'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command "'gnome-terminal'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name "'Open terminal'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding "'<Super>l'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command "'${HOME}/Configuration/Theme/toggle-dark-light'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name "'Toggle dark theme'"

#
# nautilus
#

gsettings set org.gnome.nautilus.preferences recursive-search "'never'"
gsettings set org.gnome.nautilus.preferences default-folder-viewer "'list-view'"
gsettings set org.gnome.nautilus.list-view default-zoom-level "'small'"
gsettings set org.gnome.nautilus.list-view use-tree-view true

gsettings set org.gtk.Settings.FileChooser expand-folders false


#
# gnome-terminal
#

gsettings set org.gnome.Terminal.Legacy.Settings menu-accelerator-enabled false
gsettings set org.gnome.Terminal.ProfilesList default "'b1f6a55b-ffff-4bba-9ac3-04527db074c4'"
gsettings set org.gnome.Terminal.ProfilesList list "['b1f6a55b-ffff-4bba-9ac3-04527db074c4']"

gnome_terminal_keybindings="org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/"
gnome_terminal_profile_id="b1f6a55b-ffff-4bba-9ac3-04527db074c4"
gnome_terminal_profile="org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${gnome_terminal_profile_id}/"

gsettings set "${gnome_terminal_keybindings}" move-tab-left '<Primary>comma'
gsettings set "${gnome_terminal_keybindings}" move-tab-right '<Primary>period'
gsettings set "${gnome_terminal_keybindings}" new-tab '<Primary>Return'
gsettings set "${gnome_terminal_keybindings}" new-window '<Primary><Shift>Return'
gsettings set "${gnome_terminal_keybindings}" next-tab '<Primary>space'
gsettings set "${gnome_terminal_keybindings}" prev-tab '<Primary>BackSpace'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-10 'disabled'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-1 '<Primary>1'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-2 '<Primary>2'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-3 '<Primary>3'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-4 '<Primary>4'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-5 '<Primary>5'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-6 '<Primary>6'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-7 '<Primary>7'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-8 '<Primary>8'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-9 'disabled'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-last '<Primary>9'
gsettings set "${gnome_terminal_keybindings}" toggle-menubar 'disabled'
gsettings set "${gnome_terminal_keybindings}" zoom-in '<Primary>equal'
gsettings set "${gnome_terminal_keybindings}" zoom-normal '<Primary>0'
gsettings set "${gnome_terminal_keybindings}" zoom-out '<Primary>minus'

gsettings set "${gnome_terminal_profile}" allow-bold false
gsettings set "${gnome_terminal_profile}" audible-bell false
gsettings set "${gnome_terminal_profile}" background-color "'rgb(253,246,227)'"
gsettings set "${gnome_terminal_profile}" bold-is-bright false
gsettings set "${gnome_terminal_profile}" default-size-columns 120
gsettings set "${gnome_terminal_profile}" default-size-rows 36
gsettings set "${gnome_terminal_profile}" foreground-color "'rgb(101,123,131)'"
gsettings set "${gnome_terminal_profile}" palette "[
    'rgb(7,54,66)',
    'rgb(220,50,47)',
    'rgb(133,153,0)',
    'rgb(181,137,0)',
    'rgb(38,139,210)',
    'rgb(211,54,130)',
    'rgb(42,161,152)',
    'rgb(195,190,174)',
    'rgb(7,54,66)',
    'rgb(220,50,47)',
    'rgb(133,153,0)',
    'rgb(181,137,0)',
    'rgb(38,139,210)',
    'rgb(211,54,130)',
    'rgb(42,161,152)',
    'rgb(195,190,174)'
]"
gsettings set "${gnome_terminal_profile}" scrollback-lines 30000
gsettings set "${gnome_terminal_profile}" scrollbar-policy never
gsettings set "${gnome_terminal_profile}" use-theme-colors false
gsettings set "${gnome_terminal_profile}" visible-name "'Default'"

#
# dconf-editor
#

gsettings set ca.desrt.dconf-editor.Settings show-warning false
gsettings set ca.desrt.dconf-editor.Settings relocatable-schemas-user-paths "{
    'ca.desrt.dconf-editor.Demo.Relocatable': '/ca/desrt/dconf-editor/Demo/relocatable/',
    'org.gnome.Terminal.Legacy.Profile': '/org/gnome/terminal/legacy/profiles://'
}"


#
# gnome-shell extensions
#

dconf write /org/gnome/shell/extensions/dash-to-dock/animate-show-apps false
dconf write /org/gnome/shell/extensions/dash-to-dock/apply-custom-theme true
dconf write /org/gnome/shell/extensions/dash-to-dock/hot-keys false
dconf write /org/gnome/shell/extensions/dash-to-dock/intellihide-mode "'ALL_WINDOWS'"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-trash false

dconf write /org/gnome/shell/extensions/donotdisturb-button/available-icon "'/usr/share/icons/Adwaita/scalable/status/user-available-symbolic.svg'"
dconf write /org/gnome/shell/extensions/donotdisturb-button/busy-icon "'/usr/share/icons/Adwaita/scalable/status/user-busy-symbolic.svg'"
dconf write /org/gnome/shell/extensions/donotdisturb-button/panel-icon-center false
dconf write /org/gnome/shell/extensions/donotdisturb-button/panel-icon-left false
dconf write /org/gnome/shell/extensions/donotdisturb-button/shortcut "['<Shift><Super>v']"

dconf write /org/gnome/shell/extensions/draw-on-your-screen/erase-drawing "['<Shift><Super>d']"
dconf write /org/gnome/shell/extensions/draw-on-your-screen/toggle-drawing "['<Super>d']"

dconf write /org/gnome/shell/extensions/invert-window/invert-window-shortcut "['<Shift><Super>l']"
