#!/bin/sh

set -e -u -x


#
# main interface
#

gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface clock-show-weekday true
gsettings set org.gnome.desktop.interface cursor-blink false
gsettings set org.gnome.desktop.interface gtk-key-theme "'Emacs'"
gsettings set org.gnome.desktop.interface show-battery-percentage true

gsettings set org.gnome.desktop.calendar show-weekdate true

gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 2700

gsettings set org.gnome.desktop.a11y always-show-universal-access-status true


#
# gtk settings
#

local_gtk_css_file=~/.config/gtk-3.0/local.css
if [ ! -e "${local_gtk_css_file}" ]; then
    touch "${local_gtk_css_file}"
fi


#
# input devices (keyboard, mouse)
#

gsettings set org.gnome.desktop.input-sources per-window false
gsettings set org.gnome.desktop.input-sources show-all-sources true
gsettings set org.gnome.desktop.input-sources sources "[
    ('xkb', 'us+colemak'),
    ('xkb', 'eu')
]"
gsettings set org.gnome.desktop.input-sources xkb-options "[
    'altwin:swap_lalt_lwin',
    'compose:rctrl',
    'ctrl:nocaps',
    'nbsp:level4'
]"

gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Super>apostrophe']"
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Shift><Super>apostrophe']"

gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true


#
# power
#

gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type "'nothing'"


#
# security
#

gsettings set org.gnome.desktop.notifications show-in-lock-screen false

gsettings set org.gnome.desktop.privacy hide-identity true
gsettings set org.gnome.desktop.privacy show-full-name-in-top-bar false

gsettings set org.gnome.desktop.screensaver lock-delay 300
gsettings set org.gnome.desktop.screensaver show-full-name-in-top-bar false
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "['<Super>BackSpace']"

gsettings set org.gnome.system.location enabled true
gsettings set org.gnome.system.location max-accuracy-level "'country'"


#
# gtk+ inspector
#

gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true
gsettings set org.gtk.Settings.Debug inspector-warning false


#
# window management
#

gsettings set org.gnome.desktop.wm.preferences action-double-click-titlebar "'toggle-maximize-vertically'"
gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar "'lower'"
gsettings set org.gnome.desktop.wm.preferences audible-bell false
gsettings set org.gnome.desktop.wm.preferences disable-workarounds true
gsettings set org.gnome.desktop.wm.preferences focus-mode "'click'"
gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Super>'
gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
gsettings set org.gnome.desktop.wm.preferences visual-bell false

gsettings set org.gnome.desktop.wm.keybindings close "['<Alt>F4', '<Shift><Super>q', '<Control><Super>q', '<Alt><Super>q']"
gsettings set org.gnome.desktop.wm.keybindings minimize "[]"

gsettings set org.gnome.mutter attach-modal-dialogs false
gsettings set org.gnome.mutter center-new-windows true
gsettings set org.gnome.mutter workspaces-only-on-primary true

# maximised/full screen
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Alt>F11', '<Control><Super>f', '<Shift><Super>f']"
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Alt>F10', '<Super>f']"

# left/right with </> keys (without shift)
gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Super>comma']"
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Super>period']"

# quick window cycling
gsettings set org.gnome.desktop.wm.keybindings cycle-windows "['<Super>Space']"
gsettings set org.gnome.desktop.wm.keybindings cycle-windows-backward "['<Shift><Super>Space']"

# hjkl-style window/workspace navigation; with colemak keys this is hnei, not hjkl
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Super>i']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Super>h']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Super>n']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Super>e']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Shift><Super>n']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Shift><Super>e']"

# workspaces
gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.desktop.wm.preferences num-workspaces 6
gsettings set org.gnome.shell.keybindings switch-to-application-1 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-2 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-3 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-4 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-5 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-6 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-7 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-8 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-9 "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>1']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>5']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>6']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Super>7']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['<Super>8']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Super>9']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Shift><Super>1']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Shift><Super>2']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Shift><Super>3']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Shift><Super>4']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Shift><Super>5']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Shift><Super>6']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 "['<Shift><Super>7']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 "['<Shift><Super>8']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9 "['<Shift><Super>9']"


#
# screenshots
#

gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot-clip "['Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot "['<Primary>Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot-clip "['<Shift>Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot "['<Primary><Shift>Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip "['<Alt>Print']"
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot "['<Primary><Alt>Print']"


#
# shortcuts
#

gsettings set org.gnome.shell.keybindings toggle-overview "['<Super>s']"
gsettings set org.gnome.shell.keybindings focus-active-notification "[]"

gsettings set org.gnome.settings-daemon.plugins.media-keys increase-text-size "['<Super>equal']"
gsettings set org.gnome.settings-daemon.plugins.media-keys decrease-text-size "['<Super>minus']"
gsettings set org.gnome.settings-daemon.plugins.media-keys magnifier-zoom-in "['<Shift><Super>plus']"
gsettings set org.gnome.settings-daemon.plugins.media-keys magnifier-zoom-out "['<Shift><Super>underscore']"
gsettings set org.gnome.settings-daemon.plugins.media-keys magnifier "['<Super><Shift>0']"

gsettings set org.gnome.settings-daemon.plugins.media-keys home "['<Super>g']"
gsettings set org.gnome.settings-daemon.plugins.media-keys www "['<Super>w']"

gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding "'<Super>t'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command "'gnome-terminal'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name "'Open terminal'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding "'<Super>l'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command "'${HOME}/dotfiles/theme/toggle-dark-light'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name "'Toggle dark theme'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding "'<Control><Super>v'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command "'${HOME}/dotfiles/gnome/toggle-do-not-disturb'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name "'Toggle do not disturb'"


#
# nautilus + file chooser
#

gsettings set org.gnome.nautilus.preferences recursive-search "'never'"
gsettings set org.gnome.nautilus.preferences default-folder-viewer "'list-view'"
gsettings set org.gnome.nautilus.list-view default-zoom-level "'small'"
gsettings set org.gnome.nautilus.list-view use-tree-view true

gsettings set org.gtk.Settings.FileChooser expand-folders false
gsettings set org.gtk.Settings.FileChooser sort-directories-first true


#
# gnome-terminal
#

gsettings set org.gnome.Terminal.Legacy.Settings menu-accelerator-enabled false
gsettings set org.gnome.Terminal.ProfilesList default "'b1f6a55b-ffff-4bba-9ac3-04527db074c4'"
gsettings set org.gnome.Terminal.ProfilesList list "['b1f6a55b-ffff-4bba-9ac3-04527db074c4']"

gnome_terminal_keybindings="org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/"
gnome_terminal_profile_id="b1f6a55b-ffff-4bba-9ac3-04527db074c4"
gnome_terminal_profile="org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${gnome_terminal_profile_id}/"

gsettings set "${gnome_terminal_keybindings}" move-tab-left '<Primary>comma'
gsettings set "${gnome_terminal_keybindings}" move-tab-right '<Primary>period'
gsettings set "${gnome_terminal_keybindings}" new-tab '<Primary>Return'
gsettings set "${gnome_terminal_keybindings}" new-window '<Primary><Shift>Return'
gsettings set "${gnome_terminal_keybindings}" next-tab '<Primary>space'
gsettings set "${gnome_terminal_keybindings}" prev-tab '<Primary>BackSpace'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-10 'disabled'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-1 '<Primary>1'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-2 '<Primary>2'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-3 '<Primary>3'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-4 '<Primary>4'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-5 '<Primary>5'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-6 '<Primary>6'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-7 '<Primary>7'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-8 '<Primary>8'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-9 'disabled'
gsettings set "${gnome_terminal_keybindings}" switch-to-tab-last '<Primary>9'
gsettings set "${gnome_terminal_keybindings}" toggle-menubar 'disabled'
gsettings set "${gnome_terminal_keybindings}" zoom-in '<Primary>equal'
gsettings set "${gnome_terminal_keybindings}" zoom-normal '<Primary>0'
gsettings set "${gnome_terminal_keybindings}" zoom-out '<Primary>minus'

gsettings set "${gnome_terminal_profile}" audible-bell false
gsettings set "${gnome_terminal_profile}" background-color "'rgb(253,246,227)'"
gsettings set "${gnome_terminal_profile}" bold-is-bright false
gsettings set "${gnome_terminal_profile}" default-size-columns 120
gsettings set "${gnome_terminal_profile}" default-size-rows 36
gsettings set "${gnome_terminal_profile}" foreground-color "'rgb(101,123,131)'"
gsettings set "${gnome_terminal_profile}" palette "[
    'rgb(7,54,66)',
    'rgb(220,50,47)',
    'rgb(133,153,0)',
    'rgb(181,137,0)',
    'rgb(38,139,210)',
    'rgb(211,54,130)',
    'rgb(42,161,152)',
    'rgb(195,190,174)',
    'rgb(7,54,66)',
    'rgb(220,50,47)',
    'rgb(133,153,0)',
    'rgb(181,137,0)',
    'rgb(38,139,210)',
    'rgb(211,54,130)',
    'rgb(42,161,152)',
    'rgb(195,190,174)'
]"
gsettings set "${gnome_terminal_profile}" scrollback-lines 30000
gsettings set "${gnome_terminal_profile}" scrollbar-policy never
gsettings set "${gnome_terminal_profile}" use-theme-colors false
gsettings set "${gnome_terminal_profile}" visible-name "'Default'"


#
# dconf-editor
#

gsettings set ca.desrt.dconf-editor.Settings show-warning false
gsettings set ca.desrt.dconf-editor.Settings relocatable-schemas-user-paths "{
    'ca.desrt.dconf-editor.Demo.Relocatable': '/ca/desrt/dconf-editor/Demo/relocatable/',
    'org.gnome.Terminal.Legacy.Profile': '/org/gnome/terminal/legacy/profiles://'
}"


#
# gnome-shell extensions
#

# arch linux updates
if [ -f /etc/arch-release ]; then
    dconf write /org/gnome/shell/extensions/arch-update/always-visible false
    dconf write /org/gnome/shell/extensions/arch-update/auto-expand-list 8
    dconf write /org/gnome/shell/extensions/arch-update/boot-wait 10
    dconf write /org/gnome/shell/extensions/arch-update/check-cmd "'/usr/bin/checkupdates+aur'"
    dconf write /org/gnome/shell/extensions/arch-update/check-interval 180
    dconf write /org/gnome/shell/extensions/arch-update/notify true
    dconf write /org/gnome/shell/extensions/arch-update/strip-versions false
    dconf write /org/gnome/shell/extensions/arch-update/update-cmd \
        "'gnome-terminal -e \\'sh -c \"paru -Syu; echo; echo; echo done – press enter to exit; read\" \\' '"
fi

# caffeine
dconf write /org/gnome/shell/extensions/caffeine/enable-fullscreen false
dconf write /org/gnome/shell/extensions/caffeine/show-notifications false

# dash to dock
dconf write /org/gnome/shell/extensions/dash-to-dock/animate-show-apps false
dconf write /org/gnome/shell/extensions/dash-to-dock/apply-custom-theme true
dconf write /org/gnome/shell/extensions/dash-to-dock/hot-keys false
dconf write /org/gnome/shell/extensions/dash-to-dock/intellihide-mode "'ALL_WINDOWS'"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-mounts false
dconf write /org/gnome/shell/extensions/dash-to-dock/show-trash false

# draw on your screen
dconf write /org/gnome/shell/extensions/draw-on-your-screen/erase-drawings "['<Shift><Super>d']"
dconf write /org/gnome/shell/extensions/draw-on-your-screen/toggle-drawing "['<Super>d']"

# emoji selector
dconf write /org/gnome/shell/extensions/emoji-selector/emoji-keybinding "['<Super>semicolon']"
dconf write /org/gnome/shell/extensions/emoji-selector/emojisize 32
dconf write /org/gnome/shell/extensions/emoji-selector/gender 0
dconf write /org/gnome/shell/extensions/emoji-selector/nbcols 16

# gtk title bar
dconf write /org/gnome/shell/extensions/gtktitlebar/hide-window-titlebars "'both'"

# invert window
dconf write /org/gnome/shell/extensions/invert-window/invert-window-shortcut "['<Shift><Super>l']"
dconf write /org/gnome/shell/extensions/invert-window-preserving-hue/invert-window-preserving-hue-shortcut "['<Shift><Super>l']"

# nothing to say
dconf write /org/gnome/shell/extensions/nothing-to-say/keybinding-toggle-mute "['<Super>backslash', 'Pause']"

# paperwm
gsettings_paperwm () {
    extension_id="paperwm@hedning:matrix.org"
    GSETTINGS_SCHEMA_DIR="$HOME/.local/share/gnome-shell/extensions/${extension_id}/schemas" gsettings "$@"
}
gsettings_paperwm_bind () {
    gsettings_paperwm set org.gnome.Shell.Extensions.PaperWM.Keybindings "$@"
}

if gnome-extensions list | grep -q -F -x 'paperwm@hedning:matrix.org'; then
    gsettings set org.gnome.shell.overrides edge-tiling false
    gsettings set org.gnome.mutter workspaces-only-on-primary false

    gsettings_paperwm set org.gnome.Shell.Extensions.PaperWM animation-time 0.2
    gsettings_paperwm set org.gnome.Shell.Extensions.PaperWM cycle-width-steps '[0.33333333333333333, 0.5, 0.66666666666666666, 0.8]'
    gsettings_paperwm set org.gnome.Shell.Extensions.PaperWM horizontal-margin 0
    gsettings_paperwm set org.gnome.Shell.Extensions.PaperWM use-default-background true
    gsettings_paperwm set org.gnome.Shell.Extensions.PaperWM vertical-margin 0
    gsettings_paperwm set org.gnome.Shell.Extensions.PaperWM vertical-margin-bottom 0
    gsettings_paperwm set org.gnome.Shell.Extensions.PaperWM window-gap 0

    gsettings set org.gnome.desktop.wm.keybindings cycle-windows "[]"
    gsettings set org.gnome.desktop.wm.keybindings cycle-windows-backward "[]"
    gsettings set org.gnome.desktop.wm.keybindings switch-windows "[]"
    gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "[]"
    gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "[]"
    gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "[]"
    gsettings set org.gnome.mutter.keybindings toggle-tiled-left "[]"
    gsettings set org.gnome.mutter.keybindings toggle-tiled-right "[]"

    gsettings_paperwm_bind barf-out "['<Super>period']"
    gsettings_paperwm_bind close-window "[]"
    gsettings_paperwm_bind cycle-height "['<Shift><Super>r', '<Control><Super>r']"
    gsettings_paperwm_bind cycle-width "['<Super>r']"
    gsettings_paperwm_bind live-alt-tab "['<Super>Space']"
    gsettings_paperwm_bind live-alt-tab-backward "['<Shift><Super>Space', '<Control><Super>Space']"
    gsettings_paperwm_bind move-down "[]"
    gsettings_paperwm_bind move-down-workspace "[]"
    gsettings_paperwm_bind move-left "['<Shift><Super>h', '<Control><Super>h', '<Control><Super>Left']"
    gsettings_paperwm_bind move-monitor-above "[]"
    gsettings_paperwm_bind move-monitor-below "[]"
    gsettings_paperwm_bind move-monitor-left "[]"
    gsettings_paperwm_bind move-monitor-right "[]"
    gsettings_paperwm_bind move-previous-workspace "[]"
    gsettings_paperwm_bind move-previous-workspace-backward "[]"
    gsettings_paperwm_bind move-right "['<Shift><Super>i', '<Control><Super>i', '<Control><Super>right']"
    gsettings_paperwm_bind move-up "[]"
    gsettings_paperwm_bind move-up-workspace "[]"
    gsettings_paperwm_bind new-window "[]"
    gsettings_paperwm_bind paper-toggle-fullscreen "['<Shift><Super>f', '<Control><Super>f']"
    gsettings_paperwm_bind previous-workspace "[]"
    gsettings_paperwm_bind previous-workspace-backward "[]"
    gsettings_paperwm_bind slurp-in "['<Super>comma']"
    gsettings_paperwm_bind resize-h-dec "[]"
    gsettings_paperwm_bind resize-h-inc "[]"
    gsettings_paperwm_bind resize-w-dec "[]"
    gsettings_paperwm_bind resize-w-inc "[]"
    gsettings_paperwm_bind switch-down "[]"
    gsettings_paperwm_bind switch-down-workspace "[]"
    gsettings_paperwm_bind switch-first "[]"
    gsettings_paperwm_bind switch-last "[]"
    gsettings_paperwm_bind switch-left "[]"
    gsettings_paperwm_bind switch-monitor-above "[]"
    gsettings_paperwm_bind switch-monitor-below "[]"
    gsettings_paperwm_bind switch-monitor-left "[]"
    gsettings_paperwm_bind switch-monitor-right "[]"
    gsettings_paperwm_bind switch-next "['<Super>i', '<Super>Right']"
    gsettings_paperwm_bind switch-previous "['<Super>h', '<Super>Left']"
    gsettings_paperwm_bind switch-right "[]"
    gsettings_paperwm_bind switch-up "[]"
    gsettings_paperwm_bind switch-up-workspace "[]"
    gsettings_paperwm_bind take-window "[]"
    gsettings_paperwm_bind toggle-maximize-width "['<Super>f']"
    gsettings_paperwm_bind toggle-scratch "['<Shift><Super>Return', '<Control><Super>Return']"
    gsettings_paperwm_bind toggle-scratch-layer "['<Super>Return']"
fi
