#!/bin/sh

set -e -u -x

#
# main interface
#

gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface cursor-blink false
gsettings set org.gnome.desktop.interface gtk-key-theme "'Emacs'"

gsettings set org.gnome.shell.calendar show-weekdate true


#
# keyboard layouts
#

gsettings set org.gnome.desktop.input-sources per-window false
gsettings set org.gnome.desktop.input-sources show-all-sources true


#
# security
#

gsettings set org.gnome.desktop.notifications show-in-lock-screen false
gsettings set org.gnome.desktop.privacy hide-identity true
gsettings set org.gnome.desktop.privacy show-full-name-in-top-bar false
gsettings set org.gnome.desktop.screensaver lock-delay 300
gsettings set org.gnome.desktop.screensaver show-full-name-in-top-bar false
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver '<Super>BackSpace'


#
# window management
#

gsettings set org.gnome.desktop.wm.preferences action-double-click-titlebar "'toggle-maximize-vertically'"
gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar "'lower'"
gsettings set org.gnome.desktop.wm.preferences audible-bell false
gsettings set org.gnome.desktop.wm.preferences disable-workarounds true
gsettings set org.gnome.desktop.wm.preferences focus-mode "'sloppy'"
gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Super>'
gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
gsettings set org.gnome.desktop.wm.preferences visual-bell false

gsettings set org.gnome.desktop.wm.keybindings close "['<Alt>F4', '<Super>q']"
gsettings set org.gnome.desktop.wm.keybindings minimize "[]"

# maximised/full screen
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Alt>F10', '<Super>f']"
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Alt>F11', '<Shift><Super>f']"

# left/right with </> keys (without shift)
gsettings set org.gnome.mutter.keybindings toggle-tiled-left "[]"
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "[]"

# hjkl-style window/workspace navigation
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Super>i']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Super>h']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Super>n']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Super>e']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Shift><Super>n']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Shift><Super>e']"

# numbered workspaces
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>1']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>5']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>6']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Super>7']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['<Super>8']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Super>9']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Shift><Super>1']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Shift><Super>2']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Shift><Super>3']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Shift><Super>4']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Shift><Super>5']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Shift><Super>6']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 "['<Shift><Super>7']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 "['<Shift><Super>8']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9 "['<Shift><Super>9']"


#
# shortcuts
#

gsettings set org.gnome.shell.keybindings toggle-overview "['<Super>s'']"
gsettings set org.gnome.shell.keybindings focus-active-notification "[]"

# applications
gsettings set org.gnome.settings-daemon.plugins.media-keys home "'<Super>g'"
gsettings set org.gnome.settings-daemon.plugins.media-keys www "'<Super>w'"

# screenshots
gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot-clip "'Print'"
gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot "'<Primary>Print'"
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot-clip "'<Shift>Print'"
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot "'<Primary><Shift>Print'"
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip "'<Alt>Print'"
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot "'<Primary><Alt>Print'"

# extensions
dconf write /org/gnome/shell/extensions/invert-window/invert-window-shortcut '["<Super>l"]'
