#!/bin/sh

# Set Solarized colour scheme for the first Gnome terminal profile,
# and toggle between the dark and light variants.

set -e -u

profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | head -n 1)
profile_path="/org/gnome/terminal/legacy/profiles:/${profile_id}"

dconf write "${profile_path}palette" "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(195,190,174)', 'rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(195,190,174)']"

current_bg=$(dconf read "${profile_path}background-color")

if [ "${current_bg}" = "'rgb(253,246,227)'" ]; then
    # Switch to dark
    dconf write "${profile_path}background-color" "'rgb(0,43,54)'"
    dconf write "${profile_path}foreground-color" "'rgb(131,148,150)'"
else
    # Switch to light
    dconf write "${profile_path}background-color" "'rgb(253,246,227)'"
    dconf write "${profile_path}foreground-color" "'rgb(101,123,131)'"
fi
