#!/bin/sh

set -e -u -x

if ! type gnome-extensions-cli; then
    pipx install gnome-extensions-cli
    pipx runpip gnome-extensions-cli install pygobject
fi

install_extension () {
    gnome-extensions-cli install "$1"
}

install_extension arch-update@RaphaelRochet
install_extension autohide-battery@sitnik.ru
install_extension bluetooth-quick-connect@bjarosze.gmail.com
# install_extension dash-to-dock@micxgx.gmail.com
# install_extension disableworkspaceanim@owilliams.mixxx.org
# install_extension drawOnYourScreen@abakkk.framagit.org
install_extension draw-on-your-screen2@zhrexl.github.com
install_extension espresso@coadmunkee.github.com
install_extension gtktitlebar@velitasali.github.io
install_extension emoji-selector@maestroschan.fr
install_extension mprisindicatorbutton@JasonLG1979.github.io
install_extension nothing-to-say@extensions.gnome.wouter.bolsterl.ee
install_extension sound-output-device-chooser@kgshank.net
install_extension tactile@lundal.io
install_extension tint-all@amarovita.github.com
install_extension window-app-switcher-on-active-monitor@NiKnights.com

# paperwm is a bit special
install_paperwm () {
    mkdir -p ~/Projects/gnome
    cd ~/Projects/gnome
    git clone https://github.com/paperwm/PaperWM.git paperwm

    cd ~/.local/share/gnome-shell/extensions
    ln -s ../../../../Projects/gnome/paperwm 'paperwm@hedning:matrix.org'

    # HACK: The colon in the name confuses the GSETTINGS_SCHEMA_DIR
    # environment variable used by the ‘gsettings’ tool, so trick
    # it into picking up the right directory anyway.
    ln -s 'paperwm@hedning:matrix.org/schemas' 'paperwm@hedning'

    gnome-extensions-cli enable 'paperwm@hedning:matrix.org'
}
# xxx: does not work on gnome 42
# if ! gnome-extensions-cli list | grep paperwm; then
#     install_paperwm
# fi
