#!/usr/bin/env bash

set -e -u

schema=org.gnome.desktop.notifications
key=show-banners

get_current_setting () {
    gsettings get "$schema" "$key"
}

if [[ "$(get_current_setting)" == "false" ]]; then
    gsettings set "$schema" "$key" true
else
    gsettings set "$schema" "$key" false
fi
