#!/bin/sh

# Always use list view in Finder.
defaults write com.apple.Finder FXPreferredViewStyle Nlsv

# Make ~/Library visible.
chflags nohidden ~/Library

# Disable annoying visual distractions.
defaults write com.apple.dock no-bouncing -bool TRUE
