;;; evil-colemak-basics-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-colemak-basics.el

(autoload 'evil-colemak-basics-mode "evil-colemak-basics" "\
Minor mode with evil-mode enhancements for the Colemak keyboard layout.

This is a minor mode.  If called interactively, toggle the
`Evil-Colemak-Basics mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `evil-colemak-basics-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-evil-colemak-basics-mode 'globalized-minor-mode t)
(defvar global-evil-colemak-basics-mode nil "\
Non-nil if Global Evil-Colemak-Basics mode is enabled.
See the `global-evil-colemak-basics-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-evil-colemak-basics-mode'.")
(custom-autoload 'global-evil-colemak-basics-mode "evil-colemak-basics" nil)
(autoload 'global-evil-colemak-basics-mode "evil-colemak-basics" "\
Toggle Evil-Colemak-Basics mode in all buffers.
With prefix ARG, enable Global Evil-Colemak-Basics mode if ARG is
positive; otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Evil-Colemak-Basics mode is enabled in all buffers where `(lambda nil
(evil-colemak-basics-mode t))' would do it.

See `evil-colemak-basics-mode' for more information on
Evil-Colemak-Basics mode.

`global-evil-colemak-basics-modes' is used to control which modes this
minor mode is used in.

(fn &optional ARG)" t)
(defvar global-evil-colemak-basics-modes '(t) "\
Which major modes `evil-colemak-basics-mode' is switched on in.
This variable can be either t (all major modes), nil (no major modes),
or a list of modes and (not modes) to switch use this minor mode or
not.  For instance

  (c-mode (not message-mode mail-mode) text-mode)

means \"use this mode in all modes derived from `c-mode', don't use in
modes derived from `message-mode' or `mail-mode', but do use in other
modes derived from `text-mode'\".  An element with value t means \"use\"
and nil means \"don't use\".  There's an implicit nil at the end of the
list.")
(custom-autoload 'global-evil-colemak-basics-modes "evil-colemak-basics" t)
(register-definition-prefixes "evil-colemak-basics" '("evil-colemak-basics-"))

;;; End of scraped data

(provide 'evil-colemak-basics-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-colemak-basics-autoloads.el ends here
