#!/usr/bin/env bash
# Bash Configuration

# Canonicalising symlinks requires ‘readlink -f’, which may not be
# available, e.g. on OSX (though GNU coreutils can be installed via
# Homebrew). Use a ‘good enough’ fallback in that case.
___readlink_f() {
    if \
        command readlink --version 2>/dev/null | grep -q -F 'GNU coreutils' || \
        command readlink --help 2>&1 | grep -q -F BusyBox
    then
        readlink -f "$1"
    else
        printf '%s\n' "$(dirname "$1")/$(readlink "$1")"
    fi
}

_dotfiles_root="$(dirname "$(dirname "$(___readlink_f "${BASH_SOURCE[0]}")")")"

# shellcheck disable=SC1091
source "$_dotfiles_root/bash/lib.sh"

# Paths:
# - add some dirs in $HOME
# - add dirs from Homebrew (on OSX)

export MANPATH="${MANPATH:-}"
export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc
export npm_config_cache=${XDG_CACHE_HOME:-$HOME/.cache}/npm
export npm_config_prefix=${HOME}/.local/npm

if [[ -z $MANPATH ]] && ___has manpath; then
    MANPATH+=$(manpath)
fi

if [[ $OSTYPE == darwin* ]]; then
    if ___has /opt/homebrew/bin/brew; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif ___has brew; then
        HOMEBREW_PREFIX=$(brew --prefix)
    fi
    ___path_add_if_exists PATH \
        "${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin" \
        "${HOMEBREW_PREFIX}/opt/findutils/libexec/gnubin" \
        "${HOMEBREW_PREFIX}/sbin" \
        "${HOMEBREW_PREFIX}/bin"
    ___path_add_if_exists MANPATH \
        "${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnuman"
fi

___path_add_if_exists PATH \
    ~/.local/bin \
    ~/bin \
    "${_dotfiles_root}/bin" \
    "${npm_config_prefix}/bin" \
    ~/.cargo/bin \
    ~/.pyenv/shims \
    ~/.local/share/mise/shims \
    ~/.local/share/rtx/shims \
    /opt/bin
___path_add_if_exists MANPATH \
    ~/.local/man \
    "${npm_config_prefix}/share/man"

PATH=$(_deduplicate_path_components "$PATH")
MANPATH=$(_deduplicate_path_components "$MANPATH")

# Interactive shells
if [[ $PS1 ]]; then
    # Helper to emulate "set -x" output
    _run_verbose() {
        (
            # Strip visible escape sequences from $PS4; bash prompting works differently from echo.
            printf "%b" "${PS4}" | sed -e 's/\\\[//g' -e 's/\\\]//g'
            printf '%s\n' "$*"
        ) >&2
        "$@"
    }

    join_by () {
        local IFS="$1"
        shift
        printf '%s\n' "$*"
    }

    if ! ___has rev; then
        # the rev(1) program is not available on all systems
        # https://stackoverflow.com/questions/11461625/reverse-the-order-of-characters-in-a-string
        rev() {
            while read -r line
            do
                reversed=""
                for (( i=0 ; i<${#line} ; i++ )); do
                    reversed="${line:i:1}${reversed}";
                done
                printf '%s\n' "$reversed"
            done
        }
    fi

    shorten_path() {
        # shorten a directory name. keep last n components intact and
        # truncate the components in front of it (with special
        # handling of .hidden components). add an ellipsis when the
        # value has been truncated.
        local dir head tail
        dir=$1
        n=$2
        if [[ $dir == "$HOME" ]]; then
            printf '%s\n' '~'
            return
        fi
        dir=${1##"$HOME"/}
        tail=$(printf '%s\n' "$dir" | rev | cut -d/ -f"-${n}" | rev)
        head=${dir%%"$tail"}
        if [[ -n $head ]]; then
            # shellcheck disable=SC2001
            head=$(printf '%s\n' "$head" | sed -e 's#\(\(\.\?[^/]\{1\}\)[^/]\+/\?\)#\2/#g')
            head="${head%%/}…/"
        fi
        printf '%s\n' "${head}${tail}"
    }

    # libvte uses a helper script to echo the current directory in an
    # escape sequence in the the prompt. gnome-terminal uses this to
    # open new terminal tabs/windows in the same directory.
    if ___has __vte_osc7; then
        # Redefine the function to use escape sequences that do
        # not leave visual artefacts.
        __vte_osc7 () {
            printf "\[\e]7;file://%s%s\a\]" "$HOSTNAME" "$(/usr/lib/vte-urlencode-cwd)"
        }
    else
        __vte_osc7 () { :; }  # do-nothing stub
    fi

    # Git status in prompt using __git_ps1()
    if [[ -f /usr/share/git/completion/git-prompt.sh ]]; then
        source /usr/share/git/completion/git-prompt.sh
    fi
    unset git_prompt_sh
    export GIT_PS1_HIDE_IF_PWD_IGNORED=yes
    export GIT_PS1_SHOWCOLORHINTS=yes
    export GIT_PS1_SHOWCONFLICTSTATE=yes
    export GIT_PS1_SHOWDIRTYSTATE=yes
    export GIT_PS1_SHOWSTASHSTATE=yes
    export GIT_PS1_SHOWUNTRACKEDFILES=yes
    export GIT_PS1_SHOWUPSTREAM="git verbose"

    # Time range formatting
    _fmt_seconds_elapsed() {
        local n=$1
        local output=""
        local h=$((n / 3600))
        [[ $h -gt 0 ]] && output+="${h}h"
        n=$((n % 3600))
        local m=$((n / 60))
        [[ $m -gt 0 ]] && output+="${m}m"
        s=$((n % 60))
        output+="${s}s"
        echo "$output"
    }

    _pwd_is_local_fs() {
        if [[ $PWD == /run/user/*/gvfs/* ]]; then
            return 1
        fi
        return 0
    }

    # Use a DEBUG trap to store timer information before a command is executed.
    # The _timer_start variable is cleared in the prompt command function.
    _timer_start=''
    trap '[[ -z "${_timer_start:-}" ]] && _timer_start=${SECONDS}' DEBUG

    set_prompt_command() {
        # Save exit code from previous command
        local prev_exit_code=$?

        # Color styles
        local -A style=(
            [reset]="\[\e[0m\]"
            [fg=black]="\[\e[30m\]"
            [bg=black]="\[\e[40m\]"
            [fg=red]="\[\e[31m\]"
            [bg=red]="\[\e[41m\]"
            [fg=green]="\[\e[32m\]"
            [bg=green]="\[\e[42m\]"
            [fg=yellow]="\[\e[33m\]"
            [bg=yellow]="\[\e[43m\]"
            [fg=blue]="\[\e[34m\]"
            [bg=blue]="\[\e[44m\]"
            [fg=purple]="\[\e[35m\]"
            [bg=purple]="\[\e[45m\]"
            [fg=cyan]="\[\e[36m\]"
            [bg=cyan]="\[\e[46m\]"
            [fg=white]="\[\e[37m\]"
            [bg=white]="\[\e[47m\]"
        )
        style[primary]="${style[reset]}"
        style[secondary]="${style[fg=cyan]}"

        # Error
        local prompt_err=""
        if [[ ${prev_exit_code} -ne 0 ]]; then
            local exit_status=${prev_exit_code}
            # Lookup signal numbers between 0 and 64; these are returned as
            # exit codes between 128 and 192
            if [[ ${prev_exit_code} -gt 128 && ${prev_exit_code} -lt 192 ]]; then
                exit_status=$((128-prev_exit_code))" "$(kill -l ${prev_exit_code} 2>/dev/null || printf '%s' '?')
            fi
            prompt_err="exit ${exit_status}"
        fi

        # Time since previous command
        local prompt_timer_elapsed=""
        local prompt_timer_finished=""
        if [[ -n $_timer_start ]]; then
            local seconds_elapsed=$((SECONDS - _timer_start))
            if [[ $seconds_elapsed -ge 10 ]]; then
                prompt_timer_elapsed="${style[secondary]}took ${style[primary]}$(_fmt_seconds_elapsed ${seconds_elapsed})"
            fi
            if [[ $seconds_elapsed -ge 600 ]]; then
                prompt_timer_finished="${style[secondary]}finished ${style[primary]}$(date --iso-8601=seconds)"
            fi
            unset _timer_start
        fi

        # Save history so that newly opened shells immediately see it.
        history -a

        # Hook for direnv.
        if ___has _direnv_hook; then
            _direnv_hook
        fi

        local project_dir=""
        local project_name=""
        local project_super_dir=""
        local project_super_name=""

        if [[ \
            -e /.isolate-env \
            && -n $SHELL_PROMPT_PROJECT_DIR \
            && ${PWD##"${SHELL_PROMPT_PROJECT_DIR}"} != "$PWD" \
        ]]; then
            project_dir="${SHELL_PROMPT_PROJECT_DIR:-}"
            project_name="${SHELL_PROMPT_PROJECT_NAME:-}"
            project_super_dir="${SHELL_PROMPT_PROJECT_SUPER_DIR:-}"
            project_super_name="${SHELL_PROMPT_PROJECT_SUPER_NAME:-}"
        fi

        # Show ‘super project’ name; useful for directories that act
        # as containers for projects, e.g. ~/Projects. By storing a
        # short word (or emoji!) in a file called ".project-super-name" the
        # prompt shows that marker plus the topmost child dir beneath.
        local dir
        if _pwd_is_local_fs && dir=$(_closest_parent_dir_containing .project-super-name); then
            project_super_dir="$dir"
            project_super_name=$(command cat "${dir}/.project-super-name")
            if [[ $dir != "$PWD" ]]; then
                relative_dir="${PWD##"$dir"/}"
                project_name="${relative_dir/\/*/}"
                project_dir="${dir}/${project_name}"
            fi
        fi

        # User name (only if non-standard)
        local prompt_user=""
        local prompt_sign_style="${style[primary]}"
        if [[ $USER != wbolster ]]; then
            local prompt_user_style="${style[primary]}"
            if [[ $USER == "root" ]]; then
                prompt_user_style="${style[fg=red]}"
                prompt_sign_style="${style[fg=red]}"
            fi
            prompt_user="${style[secondary]}as ${prompt_user_style}${USER}"
        fi

        # Host name (only remote without screen/tmux)
        local prompt_hostname=""
        local tt_hostname=""
        if [[ -n ${SSH_CLIENT:-} && $TERM != +(screen-*|tmux-*) ]]; then
            prompt_hostname="${style[secondary]}on ${style[fg=red]}${HOSTNAME}"
            tt_hostname="$HOSTNAME"
        fi

        # Git
        local prompt_git=""
        local is_git_dir=""
        if _pwd_is_local_fs && ___has __git_ps1; then
            local _git_ps1_output
            _git_ps1_output="$(__git_ps1 '%s')"
            if [[ -n "$_git_ps1_output" ]]; then
                is_git_dir=1
                project_dir="$(git rev-parse --show-toplevel)"
                project_name="$(basename "$project_dir")"
                prompt_git="${style[secondary]}git ${style[primary]}${_git_ps1_output}"
            fi
        fi

        # Working directory (with project info)
        local prompt_wd=""
        local tt_wd="\w"
        if [[ $PWD != "$HOME" ]]; then
            prompt_wd+="${style[secondary]}in "
            if [[ -n $project_name ]]; then
                if [[ -n $project_super_name ]]; then
                    prompt_wd+="${style[fg=blue]}${project_super_name}/"
                    tt_wd="${project_super_name}/"
                else
                    local wd_short
                    wd_short="$(shorten_path "$(dirname "$project_dir")" 3)/"
                    prompt_wd+="${style[fg=green]}${wd_short}"
                    tt_wd="$wd_short"
                fi
                prompt_wd+="${style[fg=blue]}${project_name}"
                tt_wd+="${project_name}"
                if [[ $PWD != "$project_dir" ]]; then
                    project_relative_dir="${PWD##"${project_dir}/"}"
                    prompt_wd+="${style[primary]}:$(shorten_path "$project_relative_dir" 5)"
                    tt_wd+=":$project_relative_dir"
                fi
            else
                short_pwd=$(shorten_path "$PWD" 3)
                prompt_wd="${style[secondary]}in ${style[primary]}${short_pwd}"
                tt_wd="$short_pwd"
            fi
            if [[ ! -e /.isolate-env ]]; then
                export SHELL_PROMPT_PROJECT_DIR="$project_dir"
                export SHELL_PROMPT_PROJECT_NAME="$project_name"
                export SHELL_PROMPT_PROJECT_SUPER_DIR="$project_super_dir"
                export SHELL_PROMPT_PROJECT_SUPER_NAME="$project_super_name"
            fi
        fi

        # Isolation (e.g. via bwrap)
        local isolation_warning=''
        local prompt_isolation=''
        if [[ -n ${ISOLATE_ENV:-} && -e /.isolate-env ]]; then
            local isolate_name
            isolate_name=$(basename "$ISOLATE_ENV")
            prompt_isolation+="${style[fg=green]}[${style[primary]}${isolate_name}${style[fg=green]}]"
        elif [[ -n $is_git_dir ]]; then
            isolation_warning="${style[fg=red]}not isolated"
            prompt_sign_style="${style[fg=red]}"
        fi

        # Python
        local prompt_python=""
        if [[ -n ${VIRTUAL_ENV:-} ]]; then
            local venv_name=""
            if [[ $VIRTUAL_ENV == */.direnv/* ]]; then
                venv_name="$(basename "$(dirname "$(dirname "${VIRTUAL_ENV}")")")"
            else
                venv_name="$(basename "$VIRTUAL_ENV")"
            fi
            if [[ $venv_name != "$project_name" ]]; then
                prompt_python+="$venv_name"
            fi
            unset venv_name
        fi
        if [[ -n ${PYENV_VERSION:-} && $(pyenv global | paste -sd:) != "$PYENV_VERSION" ]]; then
            local active_versions
            active_versions="${PYENV_VERSION//-dev/}"  # e.g. ‘3.15-dev’ → ‘3.15’
            active_versions="${active_versions//:/, }"  # e.g. ‘3.15:3.14’ → ‘3.15, 3.14’
            prompt_python+="${prompt_python:+@}$active_versions"
            unset active_versions
        fi
        if [[ -n $prompt_python ]]; then
            prompt_python="${style[secondary]}py ${style[primary]}${prompt_python}"
        fi

        # gpg
        local prompt_gpg=""
        if [[ -n ${GNUPGHOME:-} ]]; then
            prompt_gpg+="${style[secondary]}gpg ${style[primary]}${GNUPGHOME}"
        fi

        # background jobs
        local prompt_jobs=""
        local n_jobs n_jobs_background n_jobs_suspended
        n_jobs="$(jobs -p | wc -w)"
        if ((n_jobs > 0)); then
            prompt_jobs="${style[secondary]}bg${style[fg=red]}"
            n_jobs_background="$(jobs -p -r | wc -w)"
            n_jobs_suspended="$(jobs -p -s | wc -w)"
            if ((n_jobs_background)); then
                prompt_jobs+=" ${n_jobs_background}&"
            fi
            if ((n_jobs_suspended)); then
                prompt_jobs+=" ${n_jobs_suspended}^Z"
            fi
        fi
        unset n_jobs n_jobs_background n_jobs_suspended

        # terminal title (execution/echoing embedded in $PS1)
        local term_title=""
        if [[ $TERM == +(rxvt*|screen*|tmux*|xterm*) ]]; then
            term_title="\[\e]0;${tt_hostname:+${tt_hostname}:}${tt_wd}\a\]"
        fi

        local style_leading=""
        if [[ -n $prompt_err ]]; then
            style_leading="${style[bg=red]}"
        elif [[ -n $isolation_warning ]]; then
            style_leading="${style[bg=yellow]}"
        else
            style_leading="${style[bg=cyan]}"
        fi
        local block_leading="${style_leading}  "

        # Status line about previous command
        local status_line_previous=""
        status_line_previous+="${prompt_err:+${style[fg=red]}${prompt_err}  }"
        status_line_previous+="${prompt_timer_elapsed:+${style[fg=yellow]}${prompt_timer_elapsed}  }"
        status_line_previous+="${prompt_timer_finished:+${style[fg=yellow]}${prompt_timer_finished}  }"
        status_line_previous="${status_line_previous%%  }"
        status_line_previous="${status_line_previous:+${block_leading}${style[primary]} ${status_line_previous}}"

        # Status line with other information
        # fixme: use array and join_by?
        local status_line_current=""
        status_line_current+="${prompt_user:+ ${prompt_user}}"
        status_line_current+="${prompt_hostname:+ ${prompt_hostname}}"
        status_line_current+="${prompt_wd:+ ${prompt_wd}}"
        status_line_current+="${prompt_isolation:+ ${prompt_isolation}}"
        status_line_current+="${prompt_git:+ ${prompt_git}}"
        status_line_current+="${prompt_python:+ ${prompt_python}}"
        status_line_current+="${prompt_gpg:+ ${prompt_gpg}}"
        status_line_current+="${prompt_jobs:+ ${prompt_jobs}}"
        status_line_current="${status_line_current## }"
        status_line_current="${status_line_current:+${block_leading}${style[primary]} ${status_line_current}}"

        # Primary prompt
        PS1=""
        PS1+="$(__vte_osc7)"
        PS1+="$term_title"
        PS1+="\n"
        if [[ -n $status_line_previous || -n $status_line_current || -n $isolation_warning ]]; then
            PS1+="${status_line_previous:+${status_line_previous%% }\n}"
            PS1+="${status_line_current:+${status_line_current%% }\n}"
            PS1+="${isolation_warning:+${block_leading}${style[primary]} ${isolation_warning%% } ${style[bg=yellow]}                            ${style[reset]}\n}"
            PS1+="\n"
        fi
        PS1+="${prompt_sign_style}\\$"
        PS1+="${style[reset]} "

        # Additional prompts
        PS2="${prompt_sign_style}> ${style[reset]}"  # Secondary prompt (continuation lines)
        # PS4="${style[fg=purple]}+ ${style[reset]}"  # Output from "set -x"
        # PS4=$(printf "%b" "${style[fg=purple]}+ ${style[reset]}" \
                  # | sed -e 's/\\\[//g' -e 's/\\\]//g') # Output from "set -x"
    }
    unset PROMPT_COMMAND  # ensure it's not defined already (potentially as an array)
    PROMPT_COMMAND=set_prompt_command

    # Globbing. This makes both "echo *" (only non-hidden files) and "echo .*"
    # (only hidden files, ignoring . and ..) work as intended.
    GLOBIGNORE=".:.."
    shopt -u dotglob  # ... since setting GLOBIGNORE enables dotglob as a side effect :-(
    shopt -s extglob

    # Disable annoying beeps
    if ___has setterm; then
        setterm -blength 0 2>/dev/null
    fi

    # Completion
    for file in /usr/local/etc/bash_completion /usr/local/share/bash-completion/bash_completion /etc/bash_completion /usr/share/bash-completion/bash_completion; do
        if [[ -f $file ]]; then
            # shellcheck disable=SC1090
            source "$file"
            break  # stop after first match
        fi
    done
    if type __load_completion 2>/dev/null | grep -q XDG_DATA_HOME; then
        :  # bash-completion >2.8 automatically loads from ~.local/share/bash-completion/completions
    else
        local_completion_dir=${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions
        if [[ -d $local_completion_dir ]]; then
            for file in "${local_completion_dir}"/*; do
                if [[ -f $file ]]; then
                    # shellcheck disable=SC1090
                    source "$file"
                fi
            done
            unset file
        fi
        unset local_completion_dir
    fi
    if [[ -f /usr/share/bash-complete-alias/complete_alias ]]; then
        # shellcheck disable=SC1094
        source /usr/share/bash-complete-alias/complete_alias
    fi
    unset complete_alias_sh

    # Directory changing (and creation)
    export CDPATH=.:~/Projects
    shopt -s autocd
    ..() { cd .. ; }
    -() { cd - ; }
    cd() {
        if [[ $# == 1 && -e $1 && ! -d $1 ]]; then
            _run_verbose builtin cd "$(dirname "$1")"
        elif [[ $# == 2 && $1 != -* ]]; then
            # Two args, no options: do simple path replacement, e.g. "cd site1 site2".
            _run_verbose builtin cd "${PWD/$1/$2}"
        else
            builtin cd "$@"
        fi
    }
    _mkdir+cd () {
        mkdir --verbose --parents "$1" && cd "$1"
    }
    _cd-git-top-level() {
        cd "$(git rev-parse --show-toplevel)"
        pwd
    }
    _cd-venv() {
        : "${VIRTUAL_ENV:?}"
        cd "$VIRTUAL_ENV"
    }
    _cd-site-packages() {
        : "${VIRTUAL_ENV:?}"
        cd "${VIRTUAL_ENV}"/lib/python*/site-packages/
    }
    # Leading commas in function names make shellcheck really unhappy,
    # since leading commas are invalid identifiers… which somehow work
    # just fine in bash 🤷. work around it by using aliases.
    alias ,cd-git-top-level=_cd-git-top-level
    alias ,cd-site-packages=_cd-site-packages
    alias ,cd-venv=_cd-venv
    alias ,mkdir+cd=_mkdir+cd
    alias ...=,cd-git-top-level

    # Callback when a command could not be found.
    command_not_found_handle() {
        local cmd="$1"

        # Magic typo corrector. Handles typos like "gitp ush" and "gitpu sh".
        local autocorrect_cmds="bzr git svn"
        for prefix in $autocorrect_cmds; do
            if [[ ${cmd#"$prefix"} == "$cmd" ]]; then
                # prefix is not a prefix of the typed command
                continue
            fi
            _run_verbose "${prefix}" "${cmd#"${prefix}"}$2" "${@:3}"
            return
        done

        # Too bad
        printf "\e[0;31m%s: command not found\e[0m\n" "$1" >&2
        return 127
    }

    # History
    shopt -s histappend
    shopt -s histverify
    export HISTCONTROL=ignorespace:ignoredups
    export HISTSIZE=100000
    export HISTFILESIZE=1000000
    alias h='unset HISTFILE'

    # Require confirmation for possibly destructive operations,
    # and make mv/cp use the current directory as a target by default.
    _mv_cp_helper() {
        cmd="$1"
        shift
        if [[ $# == 1 ]]; then
            _run_verbose command "$cmd" -i "$@" .
        else
            command "$cmd" -i "$@"
        fi
    }
    mv() { _mv_cp_helper mv "$@"; }
    cp() { _mv_cp_helper cp "$@"; }
    alias rm='rm -i'
    export IGNOREEOF=1  # Require twice Ctrl-D to exit.

    # File listings
    if ___has eza; then
        alias ls='command eza --classify=auto --hyperlink'
        alias l='ls --group --long --smart-group --time-style="+   %Y-%m-%d %H:%M   "'
        alias ll='l --almost-all --extended --git'
    elif command ls --version 2>/dev/null | grep -q -F 'GNU coreutils'; then
        alias ls='ls --color=auto --group-directories-first'
        alias l='ls -l --classify --human-readable --time-style="+   %Y-%m-%d %H:%M   "'
        alias ll='l --almost-all'
    else
        alias l='ls -lhF'
        alias ll='ls -lAF'
    fi

    # grep, ripgrep, etc
    alias grep='grep --color=auto'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    export RIPGREP_CONFIG_PATH=~/.config/ripgrep/config
    rg() {
        if [[ -t 1 ]]; then
            command rg --pretty "$@" | ,pager-if-tty
        else
            command rg "$@"
        fi
    }

    # Process listings and process control
    alias psg='ps auxww |grep -i'
    complete -F _killall psg
    alias k1='kill %1'
    alias k2='kill %2'
    alias k3='kill %3'

    # common chmod invocations
    alias chmod-public='chmod u=rwX,go=rX'
    alias chmod-public-with-group='chmod ug=rwX,o=rX'
    alias chmod-private='chmod u=rwX,go='
    alias chmod-private-with-group='chmod ug=rwX,o='
    alias rchmod-public='chmod -R u=rwX,go=rX'
    alias rchmod-public-with-group='chmod -R ug=rwX,o=rX'
    alias rchmod-private='chmod -R u=rwX,go='
    alias rchmod-private-with-group='chmod -R ug=rwX,o='

    # common chown invocations
    chown-mine () {
        sudo chown "$(id -un):$(id -gn)" "$@"
    }
    rchown-mine () {
        chown-mine -R "$@"
    }

    # Alias expansion also after these commands
    alias sudo='sudo '
    alias nice='nice '
    alias xargs='xargs '

    # Editor
    if ___has vim; then
        export EDITOR=vim
        alias vi=vim
    else
        export EDITOR=vi
    fi
    alias ni=vi
    alias :q='exit'
    alias :e='$EDITOR'

    # Pager
    export LESS="--no-init --use-color"
    alias lessr='less -R'

    # Man pages
    export MANOPT="--no-hyphenation --no-justification"
    man () {
        # Format for the terminal width up to the specified maximum.
        local width
        width=$(printf "%s\n$COLUMNS\n80\n" "$(tput cols)" | command grep '^[0-9]\+$' | sort -n | head -1)
        MANWIDTH=$width command man "$@"
    }

    # Detect direnv (https://github.com/direnv/direnv). The regular loading
    # method does not cooperate well with our $PROMPT_COMMAND (it breaks $?
    # detection).
    if ___has direnv; then
        # Copied from "direnv hook bash" output:
        _direnv_hook_enabled=1
        _direnv_hook() {
            if [[ $_direnv_hook_enabled == "1" ]]; then
                eval "$(direnv export bash)"
            fi
        };
        _direnv_freeze() {
            if [[ $# -eq 1 ]]; then
                echo "direnv: setting up shell environment for directory $1"
                pushd "$1" > /dev/null || return 1
                eval "$(direnv export bash)"
                popd > /dev/null
            fi
            echo "direnv: disabling shell hook; use 'direnv thaw' to enable again"
            _direnv_hook_enabled=0
        }
        _direnv_thaw() {
            echo "direnv: enabling shell hook"
            _direnv_hook_enabled=1
        }
        complete -F _cd _direnv_freeze
        direnv ()
        {
            local command;
            command="$1";
            if [[ $# -gt 0 ]]; then
                shift;
            fi;
            case "$command" in
                '')
                    command direnv
                    ;;
                freeze | thaw)
                    "_direnv_${command}" "$@"
                    ;;
                *)
                    command direnv "${command}" "$@"
                    ;;
            esac
        }
        if [[ -n ${DIRENV_DIR:-} ]]; then
            # Reload, e.g. ensure $PATH items are in the right order
            echo "direnv: environment potentially tainted; reloading" > /dev/stderr
            direnv reload
        fi
    fi

    # Development
    alias ,is=',isolate-env shell'

    # Docker
    alias ,docker-run-throwaway='docker run --rm --interactive --tty'
    complete -F _complete_alias ,docker-run-throwaway
    alias ,docker-run-throwaway-project='docker run --rm --interactive --tty --volume "$(pwd)":/project'
    complete -F _complete_alias ,docker-run-throwaway-project
    alias ,docker-compose-up-fresh='docker compose up --force-recreate --renew-anon-volumes --pull always'
    ___docker-compose-logs() {
        less -MNRSXfi --exit-follow-on-close --mouse --use-color +F \
            <(docker compose --ansi always logs --follow "$@")
    }
    alias ,docker-compose-logs=___docker-compose-logs

    # Python
    export PYTHONDONTWRITEBYTECODE=1
    # Tell many Python projects to not use a bundled cert store.
    if [[ -e /etc/ssl/certs/ca-certificates.crt ]]; then
        export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    fi
    if ___has pyenv && [[ $(type -t pyenv) != "function" ]]; then
        # Initialize if pyenv is available but not yet loaded. After
        # initialisation, ‘pyenv’ is a shell function masking the
        # actual executable. Override pyenv's insistence on putting
        # itself at the front op the PATH; that is already set up in
        # my preferred order.
        path_before_pyenv_init="$PATH"
        eval "$(pyenv init -)"
        PATH="$path_before_pyenv_init"
        unset path_before_pyenv_init
    fi
    if ___has virtualenvwrapper_lazy.sh; then
        VIRTUALENVWRAPPER_PYTHON="$(dirname "$(readlink -f "$(command -v virtualenvwrapper_lazy.sh)")")/python"
        export VIRTUALENVWRAPPER_PYTHON
        # shellcheck disable=SC1091
        source virtualenvwrapper_lazy.sh
    fi
    if ___has register-python-argcomplete; then
        # https://kislyuk.github.io/argcomplete/
        eval "$(register-python-argcomplete ,isolate-env)"
    fi

    alias ipy=ipython
    alias pyhton=python
    py-cprofile() {
        if [[ $# -lt 1 ]]; then
            printf "Error: no Python program specified. Usage:\n\n    %s some-program --some-args\n" "${FUNCNAME[0]}" > /dev/stderr
            return
        fi
        local prog="$1"
        shift
        if [[ ! -f $prog ]]; then
            prog="$(command -v "$prog")"
        fi
        local profile_file
        profile_file="$(mktemp 'python-cprofile-XXXXXX.prof')"
        python -m cProfile -o "$profile_file" "$prog" "$@"
        echo > /dev/stderr
        printf 'sort cumulative\nstats 30\n' | python -m pstats "$profile_file" 1>&2
        echo > /dev/stderr
        echo "Profile stored in ${profile_file}" > /dev/stderr
    }
    py-pdb() {
        python -m pdb "$(command -v "$1")" "${@:2}"
    }
    py-ipdb() {
        python -m ipdb "$(command -v "$1")" "${@:2}"
    }
    pytestf() {
        _run_verbose pytest --tb=short --color=yes --looponfail --verbose --verbose "$@"
    }

    # data display and conversion
    jq() {
        if [[ -t 1 ]]; then
            command jq --color-output "$@" | ,pager-if-tty
        else
            command jq "$@"
        fi
    }
    yaml-to-json() {
        python -c 'import json, sys, yaml; print(json.dumps(yaml.safe_load(open(sys.argv[1]) if sys.argv[1:] else sys.stdin), indent=2, sort_keys=True))' "$@"
    }
    json-to-yaml() {
        python -c 'import json, sys, yaml; print(yaml.safe_dump(json.load(open(sys.argv[1]) if sys.argv[1:] else sys.stdin), default_flow_style=False))' "$@"
    }

    # open in default (gui) application
    if [[ $OSTYPE == darwin* ]]; then
        alias g='open'
    elif [[ -n $XDG_SESSION_DESKTOP ]]; then
        alias g='xdg-open'
    fi

    # Locale
    alias locale-none='unset LANG LANGUAGE'
    alias locale-en='unset LANGUAGE; export LANG=en_GB.UTF-8'
    alias locale-nl='unset LANGUAGE; export LANG=nl_NL.UTF-8'

    # Linux package management
    if [[ -e /etc/arch-release ]]; then
        # Arch Linux
        for arch_package_manager in paru pikaur yay "sudo pacman"; do
            if ___has "$arch_package_manager"; then
                # shellcheck disable=SC2139
                alias i="${arch_package_manager} -S"
                # shellcheck disable=SC2139
                alias u="${arch_package_manager} -Syu"
                break
            fi
        done
        unset arch_package_manager
        complete -F _complete_alias i
        complete -F _complete_alias u
    elif ___has apt-get; then
        # Debian and Ubuntu
        alias apt='sudo apt'
        alias apt-get='sudo apt-get'
        _apt_install() {
            _run_verbose sudo apt install -V "$@"
        }
        _apt_upgrade() {
            (
            set -e
            _run_verbose sudo apt update
            _run_verbose sudo apt upgrade -V
            )
        }
        alias i=_apt_install
        alias u=_apt_upgrade
        _apt_get_packages() {
            local cur
            cur=${COMP_WORDS[COMP_CWORD]}
            # shellcheck disable=SC2207
            COMPREPLY=($(apt-cache --no-generate pkgnames "${cur}" 2>/dev/null))
            return 0
        }
        complete -F _apt_get_packages i
    fi

    # iTerm profile tricks
    if [[ -n ${ITERM_PROFILE-} && -z ${INSIDE_EMACS-} ]]; then
        _ITERM_PROFILE_FILE=~/.config/iterm-profile
        _iterm_profile() {
            printf "\e]50;SetProfile=%s\a" "$1"
            printf '%s\n' "$1" >| "${_ITERM_PROFILE_FILE}"
        }
        dark() {
            _iterm_profile "Default"
        }
        light() {
            _iterm_profile "Light"
        }
        if [[ -e ${_ITERM_PROFILE_FILE} ]]; then
            _iterm_profile "$(command cat "${_ITERM_PROFILE_FILE}")"
        fi
    fi

    # This cat has magical powers, like a space cat flying through pizzas with bacon.
    cat() {
        if ___has bat && [[ $# -ge 1 && $1 != -* && -t 1 ]]; then
            # Arguments but no flags are specified and stdout is a terminal; perform magic.
            bat "$@"
        else
            # Transparent fall-back.
            command cat "$@"
        fi
    }

    # systemd
    alias ,sc='sudo systemctl'
    alias ,scu='systemctl --user'
    alias ,jb='journalctl --boot --pager-end --lines=all'
    alias ,jf='journalctl --pager-end --follow'
    complete -F _complete_alias ,sc
    complete -F _complete_alias ,scu

    # tmux
    tmux() {
        # Turn plain "tmux" into "tmux attach" to automatically attach a
        # session (in conjunction with "new-session" in tmux.conf).
        if [[ $# == 0 ]]; then
            _run_verbose command tmux attach-session
        else
            command tmux "$@"
        fi
    }
    alias itmux='tmux -CC attach-session'  # iTerm2 tmux support

    # Readable $PATH (or similar variables)
    echopath() {
        local value="${1:-${PATH}}"
        printf '%s\n' "${value//:/$'\n'}"
    }

    # Disable Ctrl-S/Ctrl-Q. The past is not the future.
    stty -ixon

    # Misc
    alias sc='screen -UxRR'
    alias uuid4='uuidgen -r'
    ___has sudoedit || alias sudoedit="sudo -e"
    ___has rgrep || alias rgrep="grep -r"
    ___has zstd && alias ,zstd-max="zstd --threads=0 --long -19"

    # 31337 hacking the matrix
    if ___has unimatrix && ps -p "$PPID" | command grep -q cool-retro-term; then
        unimatrix --flashers --ignore-keyboard --single-wave --speed 98
        ,tmux-hax0r
    fi
fi


#
# Host-specific Configuration
#
# Machine-specific configuration (not kept in version control). The
# bashrc-$HOSTNAME variant is useful for machine specific configuration
# if the home directory is shared over NFS.
#

for file in ~/.bashrc-local "${HOME}/.bashrc-${HOSTNAME}"; do
    if [[ -f $file ]]; then
        # shellcheck disable=SC1090
        source "$file"
    fi
done
unset file

# Force $? to be 0 (for the initial PS1)
true
