# Bash Configuration

# Keep new files and directories private by default
umask 077

# Preprend some directories inside ~ to $PATH
test -d ~/bin         && PATH=~/bin:"${PATH}"
test -d ~/.local/bin  && PATH=~/.local/bin:"${PATH}"
test -d ~/.system/bin && PATH=~/.system/bin:"${PATH}"

# Interactive Shells
if [ "$PS1" ]; then
	# Make sure $HOSTNAME is set
	test -z "${HOSTNAME}" && export HOSTNAME=`hostname`

	# Prompt and terminal title
	#
	# Color format: "background;attribute;foreground"
	# Background:   40-47
	# Foreground:   30-37
	# No color:     00
	# Attributes:   0 is normal, 1 is bold, 4 is underline, 7 is inverse
	PROMPT_DIRTRIM=3
	PROMPT_HOST_CHARS="8"
	PROMPT_PRIMARY_COLOR="00;4;32"
	PROMPT_SECONDARY_COLOR="00;1;32"
	test -f ~/.bash-prompt           && source ~/.bash-prompt
	test -f ~/.bash-prompt-$HOSTNAME && source ~/.bash-prompt-$HOSTNAME
	if [ "$BASH" ]; then
		case $TERM in
		xterm|rxvt*)
			PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'
			TERMINAL_TITLE='\e]2;\w\a'
			;;
		*)
			TERMINAL_TITLE=''
			;;
		esac
		PS1="\[${TERMINAL_TITLE}\e[${PROMPT_PRIMARY_COLOR}m\]${HOSTNAME:0:${PROMPT_HOST_CHARS}}:\w\[\e[0m\] \[\e[${PROMPT_SECONDARY_COLOR}m\]\\$\[\e[0m\] "
	fi
	unset TERMINAL_TITLE
	unset PROMPT_HOST_CHARS
	unset PROMPT_PRIMARY_COLOR
	unset PROMPT_SECONDARY_COLOR

	# History
	export HISTCONTROL=ignoredups
	export HISTSIZE=100000
	export HISTFILESIZE=100000
	alias h='unset HISTFILE'

	# Tab completion
	test -n "$BASH" && test -f /etc/bash_completion && source /etc/bash_completion
	test -n "$BASH" && test -f /usr/share/bash-completion/bash_completion && source /usr/share/bash-completion/bash_completion 
	test -n "$BASH" && test -f $HOME/.bash_completion && source $HOME/.bash_completion

	# Require confirmation for possibly destructive operations
	alias cp='cp -i'
	alias mv='mv -i'
	alias rm='rm -i'

	# File listings
	alias ls='ls --color=auto'
	alias l='ls -lFh'
	alias ll='ls -AlF'

	# Show colors in grep output
	export GREP_OPTIONS='--color=auto'

	# Process listings
	alias psg='ps auxww |grep -i '
	test -z "$BASH" || complete -F _killall psg

	# Recursive chmod
	alias rchmod-public='chmod -R u=rwX,go=rX'
	alias rchmod-public-with-group='chmod -R ug=rwX,o=rX'
	alias rchmod-private='chmod -R u=rwX,go='
	alias rchmod-private-with-group='chmod -R ug=rwX,o='

	# Alias expansion also after these commands
	alias sudo='sudo '
	alias nice='nice '

	# Vim
	if type vim &>/dev/null; then
		export EDITOR=vim
		alias vi=vim
	else
		export EDITOR=vi
	fi
	alias :q='exit'
	alias :e='$EDITOR'

	# Development
	alias m=make
	test -z "$BASH" || complete -F _make m
	export PIP_DOWNLOAD_CACHE=~/.cache/pip/
	export PYTHONDONTWRITEBYTECODE=1

	# Jhbuild
	if type jhbuild &>/dev/null; then
		alias 'jhr'='jhbuild run'
		alias 'jhbo'='jhbuild buildone'
		alias 'jhboa'='jhbuild buildone -a'
		alias 'jhboac'='jhbuild buildone -a -c'
		alias 'jhs'='jhbuild shell'
	fi

	# GUI applications
	if [ ! -z "$DISPLAY" ]; then
		alias g='xdg-open '
	fi

	# Locale
	alias locale-none='unset LANG'
	alias locale-en='export LANG=en_GB.UTF-8'
	alias locale-nl='export LANG=nl_NL.UTF-8'

	# Debian and Ubuntu
	if type apt-get &>/dev/null; then
		alias apt-get='sudo apt-get '
		alias aptitude='sudo aptitude '
		alias ac='apt-cache show '
		alias acs='apt-cache search '
		alias i='sudo $(which apt-get) install -V'
		alias u='sudo $(which apt-get) update && sudo $(which apt-get) upgrade -V'
	fi

	# Misc
	alias sc='screen -UxRR'
	alias lessr='less -R'
fi


#
# Host-specific Configuration
#
# Machine-specific configuration (not kept in version control). The
# bashrc-$HOSTNAME variant is useful for machine specific configuration
# if the home directory is shared over NFS.
#

test -f ~/.bashrc-local     && source ~/.bashrc-local
test -f ~/.bashrc-$HOSTNAME && source ~/.bashrc-$HOSTNAME
