;;; jq-format-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jq-format.el

 (autoload 'jq-format-json-buffer "jq-format" nil t)
 (autoload 'jq-format-json-region "jq-format" nil t)
 (autoload 'jq-format-json-on-save-mode "jq-format" nil t)
 (autoload 'jq-format-jsonlines-buffer "jq-format" nil t)
 (autoload 'jq-format-jsonlines-region "jq-format" nil t)
 (autoload 'jq-format-jsonlines-on-save-mode "jq-format" nil t)
(register-definition-prefixes "jq-format" '("jq-format-"))

;;; End of scraped data

(provide 'jq-format-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jq-format-autoloads.el ends here
