;;; evil-numbers-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-numbers.el

 (autoload 'evil-numbers/inc-at-pt "evil-numbers" nil t)
 (autoload 'evil-numbers/dec-at-pt "evil-numbers" nil t)
 (autoload 'evil-numbers/inc-at-pt-incremental "evil-numbers" nil t)
 (autoload 'evil-numbers/dec-at-pt-incremental "evil-numbers" nil t)
(register-definition-prefixes "evil-numbers" '("evil-numbers-"))

;;; End of scraped data

(provide 'evil-numbers-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-numbers-autoloads.el ends here
